- configure.ac
- sile.in
- src/Makefile.am
/usr/share should only contain architecture independant data.
This is a packaging requirement for various distributions.
> Put core libraries in /usr/lib/sile instead of /usr/share/sile.

- src/Makefile.am
Sorry for this, but I forgot to change all-local definition in src/Makefile.am
This prevent parallel build to work.
> Forgot to modify all-local dependency.

- core/libtexpdf-output.lua
When trying to compile the sile documentation, I was getting some weird errors:
```
libtexpdf:fatal: Invalid font: -1 (324)
``` 
Not really useful. 
After some investigation, the error comes from the fact the libtexpdf can not load a pfa version of the Utopia font.
So, I searched for Utopia references in the source without finding anything.
After some more code exploration, I found out that the default font is Gentium and that  if it's not installed, fontconfig resolves it in some cases as the Utopia font.
So, I think, loadfont should report something with the original font name if the a matching font cannot be loaded.
Aside of that, the documentation should probably list Gentium as a sile dependency. (And I should make that requirement in my fedora packages).
> Show some font info when loadfont fails.

- src/justenoughlibtexpdf.c
This is allows me to include a pdf file using `SILE.outputter.drawImage` .
It's a first step towards pdf image support; currently, pdf files cannot be included a using the image package (imagesize lacks pdf support).
> Initialize pdf_files to allow the libtexpdf outputter to use PDF files as images.

- core/cairo-output.lua
- core/libtexpdf-output.lua
- core/podofo-output.lua
- packages/image.lua
- src/Makefile.am
- src/imagebbox.c
- src/justenoughlibtexpdf.c
This enables pdf images support in the libtexpdf case.
Other outputters fallback to the imagesize package.
> In case of libtexpdf outputter, use it to compute imagesize.

- sile.in
It's easier to debug the class file you're working on, if errors are shown when you test it.
> Do not silent lua errors

- examples/chordmode.sil
- packages/chordmode.lua
Here is a new version of the chordmode package using SU.gtoke for text parsing and a kind of state machine to process the found tokens. Let me know what you think about that part.
The ``\ch`` command implementation is still buggy (See the line starting with "Complex line" in the example) and as you suggested should be implemented on top of some simple TeX like commands (to be added in another package).
I am working to fix this.
> Add a package to typeset chord name above text.

- .gitmodules
There mere act of running ./bootstrap.sh make the submodule dirty
(regenerating auto generated files and so on), which is uninteresting so
better just ignore it.
> Ignore dirty state of the libtexpdf submodule

- packages/pdf.lua
Convert PDF bookmark string from UTF-8 to UTF-16BE as specified in PDF
spec.
> Unicode PDF bookmark

- core/inputs-texlike.lua
The processing currently fails at this one-line document: `\begin[papersize=a4]{document}\end{document}%` (no new line at the end). This patch fixes that.
> Fix trailing comment at the end of the document.

- languages/tr.lua
The white paper published in TUG on Turkish hyphenation specifically
mentions the special -ecek case and similar suffixes in the context of
dealing with trailing two letter suffixes. The code, however, only
matches the two letter variants with a special case for -ecek, but
overlooks -acak which is a grammatically identical variant with the same
issues.
http://www.tug.org/TUGboat/Articles/tb09-1/tb20mackay.pdf
I also submitted this tweak to the author of the upstream LaTeX package
on CPAN where these rules originated. I don't know how slow moving that
fix will be or if there will eventually be a re-import or not, but until
then I don't see a reason not to patch it here too.
> fix Turkish hyphenation rules

- .gitignore
This is some minor housekeeping but the git ignore rules aren't catching some of the build relics. This just makes it a touch easier to keep track of what is going on during development.
I noticed somebody else had started to fix this as well so I kept their commit to credit them. Incidentally their [other in-progress feature branch](https://github.com/deepakjois/sile/tree/exp) could then be rebased for an easier comparison of what is being contributed.
> update ignore list with all relics of current build system

- examples/conv-test.lua
- examples/conv-test.txt
- examples/converters.sil
- examples/smiley.svg
- packages/converters.lua
This is a first idea of a file conversion package for SILE.
It allows you to register a converter based on file extensions, and a conversion command.
This package adds an enhanced \include command that convert a file before inclusion.
When called with a source file, it's extension is checked and the file is converted if a matching converter is found. Then the generated file is included instead of the original one.
To avoid conversion on each execution, I added a dependency on LuaFileSystem to check if the source file is newer than the target one. If needed, I can make it optional.
In fact, I have the same problem as #44 : I'm working with svg file and need to convert them to pdf using inkscape before using them in SILE. So, if I provides SILE with an enhanced \image command that uses the …
> Add converters to prepare files before inclusion by SILE.

- src/justenoughharfbuzz.c
Simon, per the discussion in #95, this adds `fullname` fields to the `face` result for the font substitution, which allows to properly load the font (to use with alternative viewers) as `family` only returns the name, but doesn't return the style.
From the documentation:
```
fullname       FC_FULLNAME            String  Font face full name where
different from family and
family + style
```
> Added font fullname to face fields (to include font style).

- .travis.yml
- README.md
- configure.ac
- documentation/sile.sil
The converters package has a dependency on the lfs module. See 65f39d49
for how it uses it. I realize this will only come up for people that use
that package, but I think it should be expected that the install
process will get everything setup to use any of the core packages that
ship with SILE at will. This lua library seems to be pretty widely used
so I don't see a problem with calling it out as a dependency. This is
something that package managers especially need to be made aware of.
> make dependency on luafilesystem explicit

- tests/balanced.expected
Fixes #125
This particular test went the opposite way as the other ones you fixed. In d0dd50f you forced five digit accuracy, in a4ae37f you rounded. Both make sense for the circumstances, but I had saved all the tests based on the default Lua 5.3 behavior. This updates the test to be the way you normalized the output.
> update regression test to match a4ae37f

- tests/bug-132.expected
- tests/bug-132.sil
Here is a test case that shows the problem reported in issue #132.
The `.expected` file has a mockup of what the value should be if it was typeset in the right location, so this is expected to fail until the bug is fixed.
> Regression test for verbatim space bug

- bootstrap.sh
the bootstrap.sh script return non-zero exit code, making it impossible
to install sile from --HEAD using brew.
```
sed: -i: No such file or directory
```
Thanks @alerque for suggesting a better fix!
> fix bootstrap.sh script failing on sed

- tests/space-after-command.expected
- tests/space-after-command.sil
See issue #105
Add two new test cases:
1. The case of \em vs. \font is currently handled differently and one
eats indentation at the start of a paragraph and the other doesn't.
2. A command trailing a line and another leading a new line does not
insert a space between sequential words as expected.
Additionally I documented what is expected of the test a little better
for ease of manual review.
> Expand test case for whitespace-around-commands

- .travis.yml
Default to with for most of the runs but do one run on Lua 5.2 without.
See issue #159.
> Run Travis tests with and without ICU

- bootstrap.sh
Fixes issue #168
We either need to use bash as the interpreter here (which would probably
be fine) or actually limit ourselves to POSIX compliant syntax.  The
double bracket test is superior in a number of ways but not available
in the POSIX subset.
> Use only POSIX shell syntax for portability

- .travis.yml
This should fix #165 by doing what I should have done in #160 which is make sure compiling SILE was able to find the ICU libraries.
Without ICU these [are failing](https://travis-ci.org/alerque/sile/jobs/75917940):
* tests/arabic-scripts.sil
* tests/bug-132.sil
* tests/bug-76.sil
* tests/bug-79.sil
* tests/mini-arabic.sil
* tests/vertical.sil
In the version with  ICU these [are failing](https://travis-ci.org/alerque/sile/jobs/75917937):
* tests/bug-76.sil
* tests/bug-79.sil
* tests/mini-arabic.sil (see issue #171)
* tests/vertical.sil (see issue #164)
That leaves us with the tests for bugs 76 and 79. I'm  looking into them but they apparently aren't as simple as having or not having ICU support. Both of those tests pass on my system.
> ICU in travis

- packages/folio.lua
- tests/balanced.expected
- tests/masters.expected
When set no page numbers are printed on the console, which doesn’t seem to a be an intended side effect.
> \nofolios should’t suppress showing progress

- core/sile.lua
- sile.in
@deepakjois already mentioned this in #184, but this in some scenarios masterFilename is getting called before initialization. This is the same fix from Deepak's original commit (5b346a6) with the comment that goes with the code line moved to match.
I didn't look very hand to see if there is a better way to fix this, but it does need to get fixed.
> Fix regression due to 820e8d9

- classes/markdown.lua
- packages/url.lua
The `url` package was providing `\url`, which in turn was calling
`\code`, but that wasn't defined (unless your document happened to do
so). The `markdown` package meanwhile did have a working definition for
`\code`. Re-arranging this means that loading any one of the packages
will actually get them each the commands they need to run.
> Unravel interdependency between packages

- packages/counters.lua
The maxlevel is nice if you just want an upper division (theChapter
instead of theChapter + theSection) but what if you want just
theSection? Or in a more common scenario if you have parts, outputting a
counter that has the chapter number without outputting the part number
is normal.
Usage to output just the last level of the counter:
SILE.call("show-multilevel-counter", {minlevel = options.level})
> Add minlevel option to truncate counter output

- classes/book.lua
- languages/en.lua
- languages/tr.lua
- packages/tableofcontents.lua
This moves English only output into the EN localization, adds a function for localizing TOC headers and adds localized strings for Turkish. Blank default strings rather than English seems like a better way to encourage properly setting the document language and adding localizations to all languages.
> Improve localization

- documentation/sile.sil
Those are attempts at some small fixes I tried to do while reading the manual. I'm not sure if all of them are right, so please review.
Especially, I'm not sure how `SILE.Length` (or `SILE.length`?) and `Glue` (or `SILE.Glue`? `SILE.newGlue`?) are intended to be named on lines ~1677-1678 (even after a cursory look in the code). But naming one in a different way than the other looks inconsequential.
> documentation/sile.sil: small fixes

- packages/leaders.lua
The previous code would output a minimum of two repetitions of the
leader even after calculating that there was only space for one. This
would push the page number out of bounds in TOC entries that filled up
most of the space. The calculation for 0× repetitions worked and
anything over 2× worked, but if there was really only space for 1×
filler it was getting output twice anyway.
> Suppress 2× repetitions of leader when there is only space for 1×

- core/nodefactory.lua
Fixes #227
A value >= 1e108 causes a "Parsing CFF DICT failed" error out of
libtexpdf.
> Make infinity smaller, but not too small

- packages/footnotes.lua
Fixes issue #231
See commit b3072fa for where this issue was introduced.
> Add push/pop state back to footnote typesetter

- packages/footnotes.lua
Previous code had a hard coded way of setting the foootnote font size to
9pt. The \footnote:atstart command could be fired up to override this,
but that fires only after the value has been set once. Additionally this
makes it hard for a class to customize and still make it easy for the
user to over-ride. A class should be able to set the default font size
while still letting the user run code of their own at start (without
having to manually include the font settings if they don't want to
override them.
Related to #204
> Make footnote font configurable

- core/harfbuzz-shaper.lua
- core/libtexpdf-output.lua
- packages/font-fallback.lua
- src/justenoughharfbuzz.c
The use of codepoint here is confusing since it is actually a glyph id
(HarfBuzz calls it that way probably because the buffer holds actual
code points before shaping).
> Rename codepoint to gid

- classes/book.lua
Without this the baseclass.endPage() is used to end only the last page
in the book, causing the running headers to show up on all but the last
page. This is fine if you happen to dump a trailing page for binding
purposes with no content anyway, but it that page happens to still have
book content it's a little lonely without headers.
> Call book.endPage() function from book.finish()

- src/justenoughicu.c
Not needed since 5597a766e9a26b6f78cecf5ccbde9fe0ac66fe9b.
> Avoid the extra UTF-16 to UTF-8 conversion

- classes/plain.lua
- documentation/macros.xml
- documentation/sile.sil
- examples/usx/usx.sil
- languages/und.lua
- languages/xx.lua
- packages/tate.lua
- packages/verbatim.lua
Fixes issue #270
This maintains some semblance of compliance with other language tagging
systems as specified by IETF BCP-47.
> Rename undefined language as 'und' rather than 'xx'

- bootstrap.sh
If a command, such as git or automake, is missing, there isn't much point in continuing.
`set -e` is [specified by POSIX][1], so we can probably assume it's present on most systems.
[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#set
> bootstrap.sh: Exit upon commain failure

- README.md
SILE's required libraries don't need to be installed with luarocks;
installing them through my system's package manager worked just fine
for me.
While here, mention what the "PDF creation library" is called and link
to it, and fix a typo.
> README.md: Tweak installation instructions

- src/justenoughfontconfig.c
After this change, [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/)
becomes available in weight=300.
Resolves https://github.com/simoncozens/sile/issues/281
> Call fontconfig for mapping CSS weights

- src/justenoughfontconfig.c
According to the [FcFontMatch documentation](https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcfontmatch.html), fontconfig can return
wrong results if these functions have not been called before.
Note: When running the regression tests on my local machine with
this change, I get some diffs for `bug-264b.sil` and `vertical.sil`.
However, when building SILE from git head without any changes,
I get the exact same errors.
> Call FcConfigSubstitute and FcDefaultSubstitute before FcFontMatch

- _config.yml
- _layouts/default.html
Fixes #294
This does _not_ allow the site to be hosted under forks on Github Pages
as it should because Jekyll there does not set the value correctly, but
it does allow a local Jekyll instance to be hosted under a subdirectory
if you can set the `--baseurl` flag. There are some other issues with
that, but this should restore the main site to full functionality.
> Fix base url so relative links work

- core/languages.lua
Even in the SILE source tree we have tons of `font[language=ar]` etc. calls for languages that don't have specific setups (yet). This at  least works to pass some data about the text through to Harfbuzz etc, blocking compilation altogether for languages we don't have yet is worse than failing gracefully.
> Fix change from ee97145d to only be warning so we don't kill existing working docs

- core/font.lua
- core/hyphenator-liang.lua
- core/utilities.lua
- documentation/sile.sil
- packages/unichar.lua
- tests/malayalam.sil
Many scripts/languages use different hyphenating character than "-". For instance Malayalam prefers non-visible hyphen. XeTeX has support for specifying the preferred hyphen per font via fontspec. Add similar functionality to SILE.
One question: it seems setting `font.hyphenchar` affects subsequent different font/language text as well unless explicitly set to something else. Is this correct, or is there a better way?
Please note: this is my first attempt to make changes to SILE and in Lua - would be great to get your feedback and whether it could be implemented better.
> SILE: font: add support for HyphenChar parameter

- classes/book.lua
- core/utilities.lua
- packages/pdf.lua
- packages/tableofcontents.lua
This takes a slightly different approach passing content to the TOC.
- The **original** model: Parse the entry down to a single string item, pass it to the TOC, then use it as a string for the PDF index and wrap it it an object again to typeset.
- The **new** model: Pass the original entry as-is to the TOC. Then reduce it to a string (by walking the entire object) for the PDF index and use the whole object minus the top level function to typeset the contents.
This approach allows chapter titles to include extra code (such as emphasized words, or in my first use case discretionary break points) in the chapter title string that actually gets used in the TOC entry. Of course having SILE code passed along to the TOC works fine for typesetting it, but not so much for cramming into the PDF …
> Pass objects to TOC

- classes/markdown.lua
- classes/plain.lua
Converting documents between formats (e.g. with Pandoc) is a kettle of
fish, but having a few standard markup tags available that have obvious
correlations in other markup languages makes the process a lot easier.
The name of `strong` was chosen to pair with our existing `em` also used
in HTML (as opposed to `textbf` which might have paired with `textit` if
we were using LaTeX as a reference).
> Add \strong for ease of document format conversion

- tests/bug-301.sil
See #301
At some point SILE changed the way it handled leading and the values
needed to re-create a similar document with things in the places that
show the problems changed quite a bit. This should create a document
that is symptomatic again.
> Update metrics so test is symptomatic of bug

- Makefile.am
Most people won't need to run this, but if we ever want to regenerate the development visualization video I prepared (see #289) this is the command to do it.
> Add make target for git history visualization

- core/length.lua
SILE may not have a use for these internally, but I keep running into times it would be nice to be able to treat a length as a number that can be multiplied and dived by some increment. Rather than having to manually convert to a number every time, it seems to make sense just to teach Lua how to handle × and ÷ operations on lengths. Given that it already handles + and -, this seem like the most expected behavior from an end user perspective.
> Restore (and fix) function to multiply lengths

- packages/tableofcontents.lua
We had a command for \tableofcontents:header to make it easy for a class
to typeset some stuff up there. This is sometimes where the command for
opening a new page (if any) is placed. Unfortunately we didn't have a
matching footer one. This adds one and sets it up to add flexibility to
the layouts a class can accomplish without having to modify the document
content and without having to do too many antics with redefining
standard commands.
I have documents that I want to typeset using the same template
(generated by Pandoc) but with different classes and sometimes the TOC
will take up a full page and sometime not. Having to change the body
content of the document is not an option in these cases and the most
logical place to put it is the same place where the control for starting
on a …
> Allow customization of TOC with a footer to match header

- src/svg.c
strncat() appends at the terminating null byte, but the very first time
“output” will contain uninitialized garbage.
> Don’t write garbage at the start of the path

- configure.ac
This change should fix building for OS X < 10.8, at the expense of disabling AppKit support on those systems.
I successfully tested this with Homebrew on OS X 10.7.5, using the following equivalent patch to `configure`:
```
--- configure~  2016-08-31 09:33:03.000000000 +0300
+++ configure   2016-10-28 11:28:14.000000000 +0300
@@ -13446,7 +13446,7 @@
cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */
-
+@import AppKit;
int
main ()
{
```
Background information is available at [Apple developer web site](https://developer.apple.com/library/content/documentation/Xcode/Conceptual/WhatsNewXcode-Archive/Articles/xcode_5_0.html), particularly "Modules for system frameworks" under the heading "Compiler".
> OS X (< 10.8): Check if compiler knows about modules (@import)

- configure.ac
Makes it easier to spot warnings in the code.
> Enable automake silent rules

- classes/bible.lua
- classes/book.lua
- classes/diglot.lua
- classes/docbook.lua
- classes/jbook.lua
- classes/jplain.lua
- classes/markdown.lua
- classes/pecha.lua
- classes/triglot.lua
- core/inputs-common.lua
- core/sile.lua
- documentation/sile.sil
- examples/byhand.lua
- examples/greek-lexicon/classes/perseus.lua
- examples/usx/classes/usx.lua
- sile.in
- tests/bug-337.lua
- tests/classes/testsidenote.lua
- tests/classes/testtwocol.lua
The current system demands that any custom classes reside in a specific place relative to the current document. This makes it impossible to include a toolkit in a project in just one folder, you have to pollute the namespace with several folders. This makes it possible to use classes that are in user specified locations so they can even be outside the current directory (referencing a common toolkit folder) or whatever.
> Allow classes to be loaded from non hard-coded paths

- examples/hyperlink.sil
- packages/pdf.lua
- packages/url.lua
This adds an `\href` command to the *url* package that can be used to make links to external URI's.
> Pdf external links

- core/break.lua
- core/inputs-common.lua
- core/inputs-texlike.lua
- core/inputs-xml.lua
- core/sile.lua
- core/typesetter.lua
- examples/osis/osis.xml
- packages/autodoc.lua
- packages/folio.lua
- packages/insertions.lua
- sile.in
This resolves my issue with #414 and makes SILE get along a lot better in a *nix environment. You can now use SILE pretty much any way you would use a any standard  POSIX utility to read/write input. This includes acting as part of a pipeline where the document comes from STDIN and the rendered PDF goes to STDOUT. For example you could run
$ echo "<sile>This is an XML string</sile>" | sile - | lpr
This feeds an XML document string into sile and sends the output straight to the default printer without fussing with intermediate files. This may sound like a party trick, but consider even for this simple trick four commands would have been run:
$ echo "<sile>This is an XML string</sile>" > doc.xml
$ sile doc.xml
$ lpr doc.pdf
$ rm doc.xml doc.pdf
This quickly gets out of hand when you have a …
> What comes in must go out

- core/colorparser.lua
- core/libtexpdf-output.lua
- src/justenoughlibtexpdf.c
Hi!
As said in #444, I tried to implement cmyk and grayscale colors in SILE.
Everything seems to work as you can see in this quick example: [colors.pdf](https://github.com/simoncozens/sile/files/785048/colors.pdf).
Might not be the best implementation as I'm a newbie in lua  but it doesn't break anything either, which is nice, I think.
So now, you can set colors as you used to but you can also specify each channel's value separated by a space (between 0 and 255, decimals separated by a comma `125.65`).
`colorparser` will then choose which type of color it is depending of the number of channels: 
`\color[color = 125]{1 for grayscale}`
`\color[color=0 0 255]{3 for rgb}`
`\color[color=255 255 0 0]{4 for cmyk}`
Should help a lot to use cmyk colors when printing pdfs even if ICC profiles are …
> Add support for CMYK and grayscale colors.

- core/break.lua
- core/inputs-common.lua
- core/inputs-texlike.lua
- core/inputs-xml.lua
- core/sile.lua
- core/typesetter.lua
- examples/osis/osis.xml
- packages/autodoc.lua
- packages/folio.lua
- packages/insertions.lua
- sile.in
This fixes #414 and makes SILE get along a lot better in a *nix environment. You can now use SILE pretty much any way you would use a any standard  POSIX utility to read/write input. This includes acting as part of a pipeline where the document comes from STDIN and the rendered PDF goes to STDOUT. For example you could run
$ echo "<sile>This is an XML string</sile>" | sile - | lpr
This feeds an XML document string into sile and sends the output straight to the default printer without fussing with intermediate files. This may sound like a party trick, but consider even for this simple trick four commands would have been run:
$ echo "<sile>This is an XML string</sile>" > doc.xml
$ sile doc.xml
$ lpr doc.pdf
$ rm doc.xml doc.pdf
This quickly gets out of hand when you have a complicated chain …
> What goes in must come out

- README.md
It was removed from the repo, I linked up the last time it was in there.
Also using rawgit otherwise github will force a download.
> readme: fix showoff.pdf link

- core/sile.lua
- sile.in
This should fix #443 by allowing multiple instances of `-I` and `-e` flags from the command line.
> Process multiple instances of command line options

- core/baseclass.lua
- core/utilities.lua
These are low priority, but they are bits of code I've been using a lot ... to the point where none of my projects work without them.
1. It turns out the standard `options` array passed to SILE commands is hard to parse for boolean options. Because of the way Lua works and loose typing, it's hard to tell the difference between an unset value and an actual explicit false value. It's easy to code up a default true value, but much harder to get a default false. Complicating matters is that sometimes the options com from TeX-flavor markup and "false" can be a string, but in Lua a string evaluates to true. The new `SU.boolean()` function makes it easier to set default values and parse options that come back to see if you got a boolean.
1. The other function, `SILE.setCommandDefaults()`, can be …
> Add some convenience functions

- core/inputs-common.lua
With different types of stuff being processed differently (passthrough
in an environment, passthrough in a command, and normal) the "stuff"
category got a more specific name. I missed one place it was referenced.
> Fix subtle bug introduced in #495

- core/inputs-texlike.lua
- packages/bibtex.lua
- tests/bug-465-a.expected
- tests/bug-465-b.sil
This should fix the issue with included TeX-flavor markup being silently dropped.
> Fix includes of TeX-flavor content

- sile.in
Without this it is easy to debug SILE running tests from _inside_ the SILE path (because the current working directory is searched first by default) but it is very hard to use a version of SILE located in a directory somewhere on the system from some other path. In my case I'm trying to test different versions of SILE on book projects and need to run `sile` from my project's directory. This sets up the search paths in such a way that I can `export SILE_PATH` and have it search that for modules and packages before using the system installation path.
> Setup paths so different checkouts can be debugged in parallel

- core/baseclass.lua
- core/typesetter.lua
- core/utilities.lua
A while ago in #312 I asked about detecting the context a command was executed from. I've experimented with several ways of doing this and this is the most useful one I've come up with so far. Overloading `SILE.process()` tends to turn up far too much noise to be useful. This hijacks the `SILE.registerCommand()` function and creates functions that are wrappers that push and pop their own names off a stack of command names.
I was going to put this tracking behind a flag on some sort, but I did some profiling on an old slow machine compiling the manual and came up with 80.82 seconds with the original sile version and 81.04 with the breadcrumb tracker. In other words the difference is not appreciable. In fact to even come up with the difference that direction I had to run both versions …
> Hansel and Gretel

- packages/pdf.lua
- tests/bug-556b.sil
As mentioned in #556 this PR fixes uninitialized pdf in case of command pdf:destination
> fixes #556 : uninitialed pdf in function pdf:destination

- documentation/sile.sil
The list is updated to refer to packages which need to be installed on a system which has never used Lua.
Modified luarocks line because at least on Ubuntu the given `apt-get` command is enough to get `sile` to compile. 
Fixes “serious” > “series” error BTW.
> List actual Debian/Ubuntu packages needed

- core/harfbuzz-shaper.lua
- src/justenoughfontconfig.c
Since fontconfig 2.11.95, fontconfig [introduced TrueType GX support](https://github.com/freedesktop/fontconfig/commit/27d61f1ddcda5543e9c6440a0f8794caa0b1eac7), which changes the meaning of `index` property in fontconfig. The field is originally used for specifying the index of the font face in a font file which contains multiple font faces. However, since 2.11.95, fontconfig start to use its higher 16-bit to hold the number of named instances available for the current face if we have a GX or OpenType variation (sub)font (which is quite similar to the [style_flags](https://github.com/aseprite/freetype2/blob/master/include/freetype/freetype.h#L905) option in freetype). However, libtexpdf does not support GX and `index` is only treated as the font face index. When font with GX feature is …
> Mask font index from fontconfig to lower 16-bit

- core/settings.lua
One of the user case is to replace the default font of the document. Since the default font is hard-coded into the script. Everytime when execute SILE.settings.reset, we will go back to that font. This behavior
is not desired when you are using book class with footnotes and folio.
For example, with the following piece of code, the master frame would be set to Source Han Serif font, while the footnotes and folio frames are still the default Gentium Plus (on my computer, it is fallback to simsun):
```latex
\begin[class=book, papersize=100mm x 100mm]{document}
\script[src=packages/lorem]
\set[parameter=font.family, value=Source Han Serif CN]
\lorem[words=10]\footnote{\lorem} \lorem[words=10]
\end{document}
```
After applying this patch, we added a `\set-default` command, which can change the …
> Add `makedefault` option to set command for changing default setting value

- .gitignore
- CMakeLists.txt
- README.md
- cmake/fontconfig.diff
- cmake/fonts_conf.cmake
- cmake/icu.diff
- cmake/lua.diff
- cmake/srlua.diff
- src/justenoughharfbuzz.c
- src/justenoughicu.c
- src/silewin32.h
This PR aims to make it possible to build SILE on Windows. The building script is written in CMake. Dependencies are fetched and built in the building process. The PR would resolve #410 and workaround #82 (by avoiding using MinGW).
Steps towards merging:
Note:
1. The dependencies are fetched with CMake `ExternalProject` commands which prefers CMake project for best integration. However, not all dependencies come with a CMake script for building. To workaround this, we are either using some unofficial git repositories for those projects, or applying a patch with CMake script and minimal neccessary changes. To summarize,
* Official package / mirror without modification:
* zlib: https://github.com/madler/zlib
* libpng: https://github.com/glennrp/libpng
* libexpat: …
> Port to MSVC with CMake script

- packages/counters.lua
ICU uses different convention for roman numeral capitalization than
SILE. This adds a translation which fixes this issue.
Closes #571
> [counters] Fix roman style capitalization

- documentation/sile.sil
- packages/pdf.lua
- src/justenoughlibtexpdf.c
I often find myself organizing PDFs by metadata. LaTeX's
`\usepackage[pdfusetitle]{hyperref}` is useful for that, so here's my
attempt at adding an equivalent to `packages/pdf`. (For verification,
I usually use `exiftool` or the stricter `pdfinfo`.)
It doesn't appear that PDF-specific details can be tested at present,
so there's no test file, but hopefully documentation/sile.sil will serve
as an example.
As before, please feel free to reject, rewrite, or take some parts.
> Allow setting PDF metadata with \pdf:metadata

- README.md
Some systems need `ldconfig` to be run to be formally informed of newly installed libraries. Hence it would be useful to advise users of this when trying to install/use by compiling from source.
Fixes #554.
> Add instruction to run `ldconfig` after install

- core/settings.lua
- core/utilities.lua
Currently `SILE.settings.set()` behaves entirely differently than `SILE.call("set", ...)`. Automatic type casting is being done in the `SILE.call("set")` implementation, but the `SILE.settings.set()` implementation handles it differently. This normalizes the two by doing the casting in the latter and making the former just call the later without doing all its own monkey business.
> Normalize set() functions

- classes/book.lua
It may sometimes be useful to exclude some sections from table of contents, this adds the ability to do it through: `\subsection[toc=false]{Not in ToC}`.
Another two proposed & related changes:
1. In my fork, I don't increment section counters when `numbering` is `false`. This works quite well in combination with `toc=false`, so I propose adding it. The current behavior could be preserved with `numbering=hidden` (or some variant which preserves backwards compatibility).
2. [Current check for `numbering` in book.lua](https://github.com/simoncozens/sile/blob/master/classes/book.lua#L102), "`if options.numbering == nil or options.numbering == "yes"`", looks like it could benefit from `SU.boolean()`. However, that function does not check for `yes/no`, only for `true/false`. I propose …
> feat(book): Add option to disable ToC entry for book section

- packages/counters.lua
Consists of two commits, I suggest to review them separately.
The main motivation for this was to expose a way to obtain a multilevel counter as string. While doing that, I have noticed an opportunity to cleanup some code duplication.
NOTE: It is pretty weird that `\show-(multilevel-)counter` commands can change the `display` of the counter permanently. Is that intentional or just a hack? It would be pretty easy to fix now.
Also, I am not sure about the exports and the `format` field on counters, as it duplicates the API. But it is IMO much nicer and easier to use. What do you think?
> counters: Improve external API and cleanup internal code

- core/utilities.lua
- languages/tr.lua
- packages/counters.lua
- src/justenoughicu.c
- tests/counters.sil
I'm working my way through things I wrote for CaSILE's `cabook` class and ran across the fact that I completely scrapped and replaced `SILE.formatCounter()`. These commits port most of the changes I made that still looked to me like improvements. My original only handled up to 4 digit numbers correctly, this has been extended up to 15 digits (Nine Hundred Ninety Nine Trillion...). I didn't know off the top of my head what comes after that in Turkish so I had to stop there. Both cardinal and ordinal output is supported.
```TeX
\set-counter[id=test,value=17264256543217]
\language[main=tr]{\show-counter[id=test,display=Ordinal]}
```
I will leave English and other languages as an exercsize for somebody else.
> Add formats and Turkish language support to counters

- core/dummy-output.lua
- core/harfbuzz-shaper.lua
- core/makedeps.lua
- core/sile.lua
- sile.in
Fixes #305.
This keeps track of every file used in the creation of a document including
... and outputs them in a format that can be included into a GNU Makefile using the `-m` flag (with at optional filename).
Note this can be used with or without the dummy `-b dummy` backend that avoids writing any actual final output so dependencies can be generated on their own or as a side effect of the last rendering pass.
> Autogenerate makefile dependencies

- core/languages.lua
This is a hold over get get us through until a permanent fix for #633 is agreed on.
In my testing (over thousands of loads) simply disabling this "feature" reduces load time by 0.01-0.015 seconds and has no measurable effect on run time for a single document.
On the flip side, as long as this "feature" is enable the English language file is simply not doing its job at all.
> Disable serialized hyphenation pattern loading

- README.md
Closes #679.
In light of the showoff document not being compiled in git any more and not even being very good (see #624) I've just linked to the example gallery page on the website instead. 
See also https://github.com/sile-typesetter/sile-typesetter.github.io/issues/2
> docs(readme): Update dead link, rawgit service shutdown

- tests/regressions.pl
Rewrite regression handler to examine the expectations file itself
rather than shelling out to (possibly unsupported) grep magic.
> chore(tests): Not all systems support grep -P, use Perl instead.

- .github/FUNDING.yml
Hey @simoncozens have you thought about enabling Github [Sponsors](https://github.com/sponsors) on your account? I have and it would be nice to link to it from this project, but I wouldn't feel right about the button showing a link to me and not to you! You can see what it would look like if we did on the [CaSILE](https://github.com/sile-typesetter/casile) repository page. The way sponsors work has no real connection to specific projects so people pick what developers they want to sponsor and for how much. The button just links to suggested people to sponsor from each project.
> chore(readme): Add Github Sponsors configuration

- README.md
Related to #717.
These link formats will have less issues with user scripts or browsers that block trackers or that sort of thing. The Google Groups UI still loads the other format later, particularly for logged in users, but this format should be more stable to link to externally.
Note this does not fix the problem with the JA group for me.
> Update Google Groups links

- core/base-shaper.lua
Fixes #604, though I am not sure if this is a correct/complete fix, as discussed in the issue.
In any case, it shouldn't break anything.
Even if this doesn't get merged, it could be useful for others facing the same issue.
> Fix rare crash when font is specified by filename

- tests/font-fallback-empty.expected
- tests/font-fallback-empty.sil
While messing with something else I noticed that loading the font-fallback package and not going on to specific a fallback stack causes a hard crash. This is undesirable behavior, so here is a test for it. This can probably be fixed (and the `KNOWNBAD` label removed) at the same time the error reporting logic is straightened out in relation to #716.
> test(fonts): Add test for font fallback package with no fallbacks

- packages/pandoc.lua
I've been using an automated book publishing workflow starting with canonical sources in Markdown, processed through Pandoc, written out to SILE for typesetting, and the result sent directly to press for some time now. A dozen books and dozens of other publications later, this workflow has been through several iterations:
1. I started with a hacked version of Pandoc that butchered the LaTeX output, crammed it in a SILE document wrapper, added some command patches so that it didn't just get thrown back up, and crossed my fingers. Books went to press this way, but it sure wasn't a process I could hand off to anybody else.
2. I then hacked together a new document writer for Pandoc (still modeled after the LaTeX one) that wrote out something a lot more SILE looking. This included ripping out …
> Create package to handle everything Pandoc might throw at us

- core/baseclass.lua
- core/frame.lua
- packages/hanmenkyoshi.lua
Partial / temporary solution for #763. Not marking as fixed because I think the overflow mechanism should be completely overhauled to re-parent content into new frames. The next page might not have frames that are any relation to the previous one and right now we assume the line shape transfers over. This guess work is right in most cases, but the inherent assumption is still a bug.
> fix(core): Guess original parent of split frames post page break

- Makefile.am
- bootstrap.sh
> Force autoconf and add sile script to install

- languages/ug.lua
- languages/unicode.lua
- lua-libraries/char-def.lua
> chore(tooling): Drop one-time-use file reader in favor of Lua's builtin

- core/text-output.lua
This fixes #773, but goes on to improve the feature with much more robust simulation of line breaks so that what would be a multi-column layout using frames in the PDF wraps all the lines the same way in the text output. This is useful in a way that extracting text from a PDF is not, and shows roughly what SILE is thinking is content.
For example you can check where hyphenation is happening with `grep -A1 -- '-$'`.
> Match space and breaks in text output to approximate PDF

- build-aux/docker-yay-runner.sh
This shouldn't be necessary because it's literally done in the
previous step, but Docker thinks it can cache steps separately and if it
doesn't detect a change to the input parameters might not actually run
that step at all. Before we try to install anything ourselves, actually
freshen the whole distro ourselves...
> chore(docker): Refresh package index before installations

- Makefile.am
- bootstrap.sh
- configure.ac
- src/Makefile.am
This should avoid or suppress some warnings during build that are confusing or distracting packagers from what the real issues are.
> Cleanup build time warning messages

- packages/pandoc.lua
In working on a SILE Writer for Pandoc ([discussion](https://github.com/jgm/pandoc/issues/6087), [PR](https://github.com/jgm/pandoc/pull/6088)) I keep bumping into things to tweak from the SILE side to match Pondoc's output. This is a running list of those tweaks, to be periodically added to `master` (so Pandoc testers can easily use it from Docker's `siletypesetter/sile:master` image), and at the very least merged when the writer is upstreamed into Pandoc master (and released to a stable build version before Pandoc support lands).
> Add more Pandoc goodies

- build-aux/git-version-gen
Building from a git clone worked before, but some distro packages (Arch Linux `sile-git` for example) use a sparse checkout without all the branches available. This throws git warnings for the branch names that don't have corresponding repository data, but they can be ignored as long as the current HEAD gives us something meaningful.
> fix(build): Fix version detection in sparse git checkouts

- .gitignore
- Makefile.am
- package-lock.json
The v0.10.2 release tarball had a couple issues. Most notably a race condition in the build process meant it assembled a list of files to package before it got the Lua modules ready for bundling. Because of the bug in the release number bumping I re-ran the clean steps in the middle of the release process and ended up with a source tarball that was _too_ clean. This includes fixes so that can't happen again, `make dist` should work on it's own without having run `make` or anything else past `./configure`.
Also closes #816 (broken upstream, workaround included here until it gets fixed).
> Fix release snafu

- build-aux/git-version-gen
Previous fix got us into the case statement but didn't provide any useful information once we got there. This provides *something*, at least.
> fix(build): Fix version detection in sparse git checkouts (#803)

- core/typesetter.lua
- tests/bidi.expected
Found a bug while running an old bidi test, which should also be checked in.
> fix(typesetter): Make `typesetter.breakwidth` a measurement

- spec/surrogate_spec.lua
- src/justenoughicu.c
Fixes #839. We were modifying a loop variable while in the loop, meaning
that we didn't run right to the end of the string.
> fix(core): Return correct length from icu.bidi_runs with surrogate pairs

- languages/cs.lua
- languages/en.lua
- languages/tr.lua
- packages/tableofcontents.lua
Fixes #848.
This localization system _works_ but I consider it an ugly hack and am only pushing this through as a stand-in until #675 is ready for production.
> fix(languages): Localize TOC title functions

- core/length.lua
Closes #838.
This is really only a weak mitigation to not cause surprise breakage in older projects, but there is a separate issue for the overhaul that will fix this properly. See #732.
> chore(measurements): Allow casting a length from a glue

- Dockerfile
Docker Hub did something upstream a week or two ago that makes their filesystem mounts incompatible with fresh GNU coreutils. Local builds of Docker images have still been working perfectly. This revives the automatic builds on Hub.
Revert when [upstream issues](https://github.com/archlinux/archlinux-docker/issues/32) are sorted out.
> Revive Docker Hub builds

- core/frame.lua
@simoncozens [mentioned in chat](https://gitter.im/sile-typesetter/sile?at=5ea401e8e5ed621d4ddcbd62) he'd hit an infinite loop. I'm guessing this fixes it, no?
> fix(frames): Avoid possible infinite loop when looking for a frame

- documentation/sile.sil
I realized today, after spending some time, that a file included with `\include` should have `<sile>` as its root tag. (Or any tag in the case of TeX-like flavour, provided there is one root.)
I propose to document this in the manual.
This commit also adds `.sil` and `.xml` extensions to the included files in the example. I am aware that SILE has mechanisms to detect the format independently of the extension, but as-is, the example suggests that you can write `\include[src=chap1]` when the actual file is `chap1.sil` or `chap1.xml`. I believe that is not the case.
> Document some facts about \include

- core/nodefactory.lua
Attempting to call a `SILE.nodefactory` function that doesn't exist
would cause a crash with an irrelevant error message:
```
\begin[class=plain]{document}
\script{
SILE.settings.set("document.parskip", SILE.nodefactory.foobar())
}
\end{document}
```
```
This is SILE v0.10.4.r10-ge9dcf23-dirty
<depr.sil>
! SILE.nodefactory.foobar() was deprecated in SILE v0.10.0. Please use SILE.nodefactory.foobar() instead. nil at depr.sil:3:1: in \script
Error detected:
...ile/master.local_install/share/sile/core/nodefactory.lua:667: attempt to call a nil value (local 'old_constructor')
```
This makes it crash with the actually helpful message:
```
This is SILE v0.10.4.r10-ge9dcf23-dirty
<depr.sil>
Error detected:
[string "..."]:2: attempt to call a nil value (field 'foobar')
```
> fix(nodes): Fix calling non-existent nodefactory function

- core/baseclass.lua
- core/inputs-common.lua
The bug in #535 is due to a `\process` from a macro being evaluated after the macro finished executing.
A possible solution to that is to replace every occurrence of `\process` by the argument before processing the body. However, macros can also take functions as their arguments, so this works if `SILE.process` accepts ASTs containing functions.
So this fixes #535. The implementation also allows for several occurrences of `\process` in a macro.
> Revamp macro system to fix scope extrusion bugs

- Makefile.am
Previously the benchmark target only worked if you specified 7 character SHAs. This both cleans up the default so that a plain `make benchmark` works to compare the current and previous commits, and allows the variables to take any valid git reference, whether a SHA or tag or branch name:
```sh
$ make benchmark
$ make benchmark BASESHA=master
$ make benchmark BASESHA=HEAD~5
$ make benchmark HEADSHA=foo
$ make benchmark HEADSHA=v0.10.4 BASESHA=v0.10.3
```
> Fix & make benchmarking more ergonomic

- Makefile-fonts
- Makefile.am
- package-lock.json
- package.json
- packages/font-fallback.lua
* Closes #877
* Closes #878
* Closes #879
----
chore(tooling): Bump standard-version from 7.1.0 to 8.0.0
Bumps [standard-version](https://github.com/conventional-changelog/standard-version) from 7.1.0 to 8.0.0.
- [Release notes](https://github.com/conventional-changelog/standard-version/releases)
- [Changelog](https://github.com/conventional-changelog/standard-version/blob/master/CHANGELOG.md)
- [Commits](https://github.com/conventional-changelog/standard-version/compare/v7.1.0...v8.0.0)
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
----
chore(tooling): Bump conventional-changelog-cli from 2.0.31 to 2.0.34
Bumps [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog) from 2.0.31 to 2.0.34.
- [Release …
> chore(tooling): Bump development environment dependencies

- .github/workflows/build.yml
- Makefile-luarocks
- Makefile.am
- bootstrap.sh
- build-aux/list-dist-files.sh
Closes #951.
This is a bit awkward, but I've been thinking about this now and then for years and nothing better has occurred to me. Fighting automake is not fun, using it as intended is actually not too bad. This punts most of the ways we were trying to be too smart for it to a shell script.
The biggest downside is currently you can't skip straight from `./configure` to `make dist`, you have to `make` in between. Working on that bit, maybe...
> Remove (most) of the wildcard hacks from automake

- Dockerfile
- Makefile.am
- README.md
- build-aux/docker-entrypoint.sh
...because they were borked in the last releases. Turns out SILE built fine, but the install step didn't always get everything in place. This could have affected some other builds toe (specifically ones that bundled Lua libraries instead of using system ones and didn't do anything extra between configure and `make install`. Any extra things (`make check` or a second `make` pass or whatever) was making the problem go away, which made it hard to spot in development. Running `make check` even was masking the fact that there was a problem before the second invocation of `make`.
Closes #955.
> Fix Docker builds

- .luacheckrc
- configure.ac
- core/harfbuzz-shaper.lua
- core/sile.lua
- core/utilities.lua
- lua-libraries/bitshim.lua
This is to smooth the way for Lua 5.4 support (see #668 and #929), inspired by [discussion here](https://github.com/keplerproject/lua-compat-5.3/issues/48). The `bit32` Lua Rock actually tries to be a shim providing Lua 5.2-like functions to Lua 5.1, but it is problematic on newer Lua's that subsequently deprecated that module. It isn't that easy to supply a module when the VM is lying to you about whether the module is already builtin or not.
This explicitly moves all out usage to a shim where we can handle how to shim each version on our own. This will now use `bit32` to shim Lua 5.1, but use the built in language operators in Lua 5.3+. These operations aren't technically 100% equivalent, but they work for what we are doing with them.
> Refactor Lua bitwise operations using explicit shim

- core/hyphenator-liang.lua
- core/nodefactory.lua
- core/utilities.lua
- packages/inputfilter.lua
* This could do with a test.
* I tried to find other examples where we are using pairs() on AST content, but didn't see any. A review would be helpful.
> Fix #532 by sorting table keys when processing content

- .github/workflows/build.yml
- Dockerfile
- Makefile-fonts
- Makefile-luarocks
- Makefile.am
- bootstrap.sh
- build-aux/decore-automake.sh
- build-aux/list-dist-files.sh
Closes #968.
...Is the *actual* fix for #961.
...Has been underlying various issues we've had for a long time, but was made a lot more obvious by the refactor done in #965 for #964 because the data that needed to be cleared was previously mixed in with another list of files that was otherwise valid.
...Started turning up in more scenarios because of the work in #953 to fix #951. This was the right thing to do, but our previous hackery before was keeping the problem from showing up by (accidentally) make reruns where the second pass was fixing what the first one broke. Cleaning that up just make the underlying problem surface in more places.
> fix(build): Ship blank lua_modules install list in source packges

- packages/unichar.lua
- tests/bug-979.expected
- tests/bug-979.sil
> fix(packages): Combine unichar output with existing unshaped node

- core/utilities.lua
Closes #985.
This is a follow up to #974 which itself used a non-deterministic sort! This makes sure array values come before labeled table values in the sort.
> fix(utilities): Use deterministic sort for sorted pairs

- build-aux/list-dist-files.sh
- core/makedeps.lua
- core/sile.lua
When the manual split into sections per chapter I noticed `make docs` wasn't rebuilding the manual when only a chapter changed and not the main source document. It turns out we were collecting all sorts of dependencies from font files to Lua modules, but `\include` was falling through the cracks.
On review we were not throwing any errors when asked to add dependencies that couldn't actually be found, we just weren't adding them. That means when the path resolver was failing (as was the case for `*.sil` includes) they just weren't getting marked.
I dealt with the case where we can ignore the failures (Lua modules provided by the VM) separately and refactored the path handling code so it covers our own bases more effectively.
> Overhaul dependency tracking

- .gitignore
- .travis.yml
In my local testing this is 4× to 5× faster generating coverage stats over our busted and regression tests. That should help out Travis just a bit.
> Use cluacov instead of just luacov for coverage tests

- .travis/setup_lua.sh
Fixing the same problem two ways makes it broken again. We can't both
use full version paths *and* tell the build system to only install
non version suffixed binaries. That worked for LuaJIT because the
Makefile tries to do both anyway, but for regular Lua we need one
solution or the other.
> ci(travis): Revert double fix that broke regular Lua

- packages/svg.lua
1. The previous incantation for including SVG files only allowed sizing them by height. This now allows calculating the scale factor by width as well. Somebody we should support both but that requires SVG manipulation I couldn't figure out yet. Also there are rotate and skew options we could handle as well someday, but this PR only adds the width feature.
2. I renamed `\include-svg-file` to just `\svg`. See commit message on 4837b06 for rational.
> Allow scaling SVG's by width, shorten registered command name

- core/libtexpdf-output.lua
I've been bothered before trying to figure out which way I was off with crop mark alignment. 0.5pt isn't much, but when a debug line is drawn with it's width all on one side of the actually thing rather than centered it can make a difference.
Also reused rule drawing code that got a revamp to draw fewer lines to get the same output.
> Draw debug boxes where they *actually* are

- documentation/c03-input.sil
- documentation/c06-macroscommands.sil
- documentation/c09-concepts.sil
- documentation/macros.sil
> Document better stair logo and \kern command

- classes/book.lua
- packages/pdf.lua
Closes #1030
I can think of at least ~~two~~ three problems with this solution:
1. It finds the exact height of the line, but the user might *expect* some white space.
2. ~~It will backfire if the page advance direction is BTT.~~ (fixed)
3. In the case of ... I don't know ... drawing rules or some other manual output routine this might *not* be what you want. The current cursor location on the baseline might be what is actually called for in some cases.
For most cases this is probably better than the default, but long term it probably needs revisiting.
> Refine placement of PDF‌ bookmarks

- documentation/c10-classdesign.sil
The brace was already closed the line before. Copying this from the PDF into a text editor will result in unbalanced braces.
> docs: Remove superfluous } in c10-classdesign.sil

- documentation/c09-concepts.sil
Replacing `r` with `content` makes the example code work. This aligns the code with the prose above:
"We will use the boundaries of [the content] frame to declare our columns"
> docs(manual): Fix two-column layout example

- core/tracestack.lua
Work continues on #1065 and elsewhere to actually port our code to proper Penlight class usage, but this is an emergency fix that needs to get rolled into a release ASAP. The idiosyncratic way I worked around issues with the bug in old versions of Penlight regarding class inheritance turns out to be even weirder than I imagined. I inadvertently sidestepped the 'parent constructor' issue by making everything a grand-parent with no true parent classes. Hence now that in Penlight 1.9.0 constructor inheritance actually works properly we aren't actually getting anything inherited.
A bigger set of changes that fixes the idiosyncratic usage will be upcoming, but this should allow distros that updated to Penlight 1.9.0 already to keep using SILE.
> Patch Penlight usage for forward support

- action.yml
It is not urgent to cut a release for this because the syntax we documented for usage as a GitHub Action actually works now, but we won't show up in the Marketplace with push-button installation options until this is fixed.
> chore(actions): Rename GH action to not match somebody's username

- classes/markdown.lua
- packages/verbatim.lua
This input:
```sile
\begin{document}
\script[src=packages/url]
Let’s try typesetting a URL: \url{https://sile-typesetter.com}.
And now a little bit of \code{inline code}.
And now a \verbatim{code block} inside normal text.
\end{document}
```
currently creates this output (using current master; zoomed in a bit):
With this PR applied, the output looks like this:
> fix(packages): \verbatim:font can process text

- configure.ac
Using `==` to compare strings is a completely pointless ksh-ism and bash-ism.
> Fix test arguments

- src/Makefile.am
The whole internals of .libs are an implementation detail of libtool. I'm leaving the whole `to_copy` mess for now as it doesn't actually break something for pkgsrc, but the dependency certainly does.
> Don't abuse libtool internals

- LICENSE
- core/typesetter.lua
This is *probably* moot either way given my access to the GitHub org, but see the commit message for my reasoning. I'm dealing with a repository transfer situation right now using Github's [Deceased User Policy](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-deceased-user-policy). Even though the repository owner was quite accepting of contributions and a number of people were involved during his lifetime, the lack on anything explicit naming other parties as being authorized to act on behalf of the project has made the whole process difficult.
@simoncozens if this sounds sane to you I think I'll leave you to merge this one so your name is on the merge commit.
> Update license holder (and revert overly aggressive Javascript→Lua port)

- classes/plain.lua
600 weight is traditionally Semibold, Bold is 700. Since relatively few fonts have Semibold instances at all I think most people got what they were expecting to get out of \strong — the Bold as the nearest rounded up weight available. For fonts with actual Semibold faces this is just wrong.
----
See https://github.com/alerque/libertinus/pull/398
Embarrassingly I have nobody to blame but myself for this. It bisects to my commit 043572ad.
> fix(classes): Define \strong weight=700, not 600

- packages/tate.lua
- tests/bug-1101.expected
- tests/bug-1101.sil
Fixes #1101. Arguably breaks vertical Arabic in Japanese, but to be fair it was broken already.
> Turn off complex flag for items in \latin-in-tate

- core/inputs-common.lua
- core/sile.lua
- sile.in
- refactor(cli): Swap stdlib opts parser for cliargs
- chore(cli): Work around parsing limitation in cliargs
> Redo CLI arg parsing without stdlib

- configure.ac
- fix(build): Run autoupdate to fix autoconf issues
- chore(deps): Bump libtexpdf module so autoconf versions match
> Match autoconf versions between SILE and libtexpdf

- Dockerfile
- Makefile.am
- build-aux/bootstrap-docker.sh
- hooks/build
* Update base image and switch to tagged releases
* Move dependency list to place it doesn't have to be repeated
* Use hook to build so Docker Hub and locally built containers match
* Work around new GitHub Actions limitations
* Reuse utility scripts from Fontship & CaSILE
* Normalize intermediate container names for easier cross-project diffs
* Rewrite container tags based on autoconf binary renaming
* Package everything necessary to build Docker container in source dist
> Overhaul Docker build

- core/font.lua
- documentation/c05-packages.sil
- packages/color-fonts.lua
- tests/bug-1142.expected
- tests/bug-1142.sil
This adds a post-load hook which is called on a font the first time it is loaded. So far the hook parses the OpenType tables, and loads the `color-fonts` package if a COLR table is found. This PR will fix #1142.
> Add font hooks, auto-load color-fonts

- .commitlintrc.yml
- .github/dependabot.yml
- .github/workflows/commitlint.yml
- package.json
- ci(deps): Block dependabot notifications for rejected updates
- chore(deps): Bump developer-only tooling
- ci(actions): Bump commitlint action
- chore(tooling): Update commitlint scopes and help messages
> Bump CI actions and developer deps

- packages/pandoc.lua
This is a cheap hack to work around space hacks in non-Unicode document
formats. Long term getting the Pandoc Writer to output good Unicode
would be a better option, but there are some barriers to that happening
easily and working in all the places this hack is expected to work.
> chore(packages): Handle Pandoc's space hacks

- core/units.lua
I ran into "twip" as a unit converting some other document formats. It would be easy enough to do the math during format conversion, but I don't see any downside to SILE having out of the box support for standardized units.
> Add some smaller units

- packages/counters.lua
`Alpha` was not listed before, despite its being a valid display type.
> docs(packages): add available counter display type

- packages/grid.lua
Previously when calculating the space toadd in makeUp, a cursor positioned exactly at a multiple of the gridSpacing would insert a full gridSpacing vglue, even when a zero vglue would also maintain proper spacing.  In other words, the range of possible values of toadd was (0, gridSpacing].
This change modifies the range of toadd to instead be [0, gridSpacing), which prevents the addition of unnecessary space.
> grid.lua: Don't add a full gridSpacing where none would suffice

- core/utilities.lua
BREAKING CHANGE: Previous return value for breadcrumbs:contains() was
just an depth index with -1 indicating no match. This made sense when
I wrote it, but coming back to it for a new project I expected a boolean
return value. Returning two values seems like the best option, but given
the function naming it seemed to make sense to return the boolean first,
hence the API breakage.
> refactor(utilities)!: Change breadcrumbs:contains() to return <bool, index>

- core/nodefactory.lua
- packages/pandoc.lua
I just tried to run some very old SILE project code on a current SILE release and it crashed and burned. Somehow I botched these deprecations a long time ago because the deprecation would work fine ... if you get past the crash produced by the bogus warning function.
> fix(core): Avoid crash on warn by using correct function

- core/settings.lua
- languages/fr.lua
I tested everything *before* tagging v0.11.0, but it started failing tests *after* tagging leaving a release that doesn't pass its own test suite. This is because we were using an interface we deprecated.
> Remove deprecated syntax in French language settings

- Makefile.am
- configure.ac
We didn't change anything in our configure, but with the v0.11.0 release cycle Homebrew is having issues building --- notably on the ARM architecture. Something about the POSIX mode shell is different there. This isn't actually figuring out what the deal is, but it does tone things down on our end to a more tried and true path. Even if what we were doing *should* have worked, for our part as an upstream it is easier if we don't rock the boat and make things hard downstream.
> Cleanup autotools usage

- README.md
- documentation/c02-gettingstarted.sil
- docs(readme): Update Arch Linux info with official package
- docs(readme): Say a little more about Nix
- docs(manual): Update Arch Linux info with official package
- docs(manual): Document NixOS and Linuxbrew alternatives
- docs(manual): Add Void Linux installation note
- docs(manual): Fix typo in version taga syntax
> Document SILE hitting the official Arch Linux repositories

- classes/book.lua
- packages/pdf.lua
- packages/tableofcontents.lua
A proposal covering main aspects of #1054 
The distinct features are in separate commits:
1. Fix for the book class: unnumbered sections shouldn't increment the counters, so one can have, e.g. a "Prologue" and then a "Chapter 1")
2. The book class passes the section number to the `\tocentry`.
3. Table of contents support for:
- depth control
- configuration for showing the section numbers in TOC entries 
4. Table of contents support for:
- option for TOC entries to be turned into links if the pdf package is loaded
5. Finally, output a warning to console if SILE needs to be rerun to update the TOC.
> Tableofcontents leveraged

- core/languages.lua
- languages/hy.lua
Hey @simoncozens I'm not sure what bottle of good stuff you opened on August 16th, 2018 when you added 3c0dfe35 but if you have any more of it around feel free to invite me ;-)
> Correct Armenian support to use ISO 639 code ‘hy’

- core/sile.lua
- sile.1.in
See #1224.
This does not correct the problem, only documents the actual behavior. Since most of our proposed solutions actually involve a change from this anyway, at least aligning the documentation with what we're actually doing should be a place to start. This is especially important since a release is immanent and any changes to this behavior might not make the cut.
> Make docs match actual CLI behavior

- azure-pipelines.yml
I'm tired of seeing a red X for something we're not currently bothering to even look at, much less expect to work. Also it takes time to even fail and wastes electrons.
As soon as anybody works on the Windows build we can enable this again.
> ci(azure): Disable Windows CI until somebody actually works on it

- packages/url.lua
Here is my proposal for #1229 - Compared to the ticket, I have ended up adding a bit more flexibility. Sounds good to me in all my tests so far (but I can't have a test submitted, as the url package needs the pdf package which needs the libtexpdf backend, not the debug backend - If I am not mistaken).
Besides a brute force test (see below), looks decent too in my "test" article:
(I would have preferred the `_` tto have a break after it, not before, but toying with the penalty settings, it was not much better with a very dense line, so I think they are quite OK finally... But of course the default penalties are at best a wild guess)
The brute force test, if one wants to play with it - 12 pages of URLs :smile_cat: - the decent scenario being of course the last.
```
\begin[papersize=6in x …
```
> feat(packages): URLs are allowed many more breakpoints

- packages/math.lua
- packages/math/typesetter.lua
This changes the default script style for `\mi` to upright when the content is more than one character, so `\mi{sin}(\mi{x})` is sin(*x*) instead of *sin*(*x*).
MathML considers function names to be identifiers and uses U+2061 to add a space between the function name and argument in cases like sin *x*.
> Use italic mathvariant for \mi only if the content is a single character

- Makefile.am
- classes/jplain.lua
- core/base-shaper.lua
- core/baseclass.lua
- core/languages.lua
- documentation/c08-language.sil
- languages/ja.lua
- packages/autodoc.lua
- packages/color-fonts.lua
- packages/font-fallback.lua
- packages/math.lua
- packages/ruby.lua
- packages/tate.lua
- tests/bug-244.expected
- tests/bug-244.sil
Fixes #1214
The only problem right now is this doesn't actually work and I don't understand why. I tried adding it to the whole document verbatim:font command and also adding it inside the specific verbatim block in question, nothing is actually working.
> Add Symbola as fallback for math in code samples

- packages/math/base-elements.lua
```
\begin[mode=display]{math}
\munder{base}{subsubsubsub}
\end{math}
```
Using `\munder{base}{sub}` with sub wider than base (as in the above example) produces this error:
```
/usr/local/share/sile/packages/math/base-elements.lua:695: attempt to index a nil value (local 'widest')
```
This fixes that.
> fix(math): Fix underover error with sub wider than base but no sup

- core/utilities.lua
My lowercase roman numerals were showing up with undotted-i'ss in
Turkish. Oops. Any time we're converting an integer to roman numerals
the output text language needs to be Latin.
> fix(utilities): Set language of roman numerals to Latin to avoid casing issues

- core/settings.lua
- packages/pandoc.lua
Many functions *want* to manipulate the settings environment for future
paragraphs. (Think a heading that sets \noindent for future paragraphs.)
Having everything isolated is nice it its own way, but that's not why
SILE is written in Lua.
This isolates the things that are clearly meant to be so but lets
everything else run (mostly) free.
> fix(packages): Don't over-isolate functions run in Pandoc imports

- core/typesetter.lua
A frame isn't overfull if everything already fit and we have nothing more to add.
> Suppress incorrect overfull warning

- packages/math/base-elements.lua
- tests/math-fractions.expected
- tests/math-fractions.xml
In math/base-elements.lua, elements.fraction is written to support not receiving a numerator or denominator. The support is incorrect/doesn't function, though; in shape, if the numerator or denominator is missing, shape will set other to nil, then crash on trying to access other.width and trying to set other.relx.
This doesn't matter *in practice*, because the only caller to elements.fraction is math/typesetter.lua, which fails earlier if there's a missing numerator or denominator:
```
local children = convertChildren(content)
if #children ~= 2 then SU.error('Wrong number of children in mfrac: '
..#children)
end
return b.fraction(children[1], children[2])
```
> Assumes that fractions have both a numerator and denominator

- azure-pipelines.yml
I'm far from an expert on this…just couldn't figure out how to stop telling `cmake` an explicit version (seems impossible), so couldn't use `windows-latest`, so went with `windows-2019` so it doesn't randomly break in future.
Cf. https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
Closes #1282.
> ci(azure): Update to `windows-2019` before deprecation

- packages/color-fonts.lua
Closes #1147.
I had been struggling with this bothersome bug for quite a while, it really was hampering development of FRB American Cursive. I tried to fix it scores of times, but my attempts were way too complicated. Reading over the code again this fine evening, I discovered the error to be extremely elementary. :-D Hooray!
> fix(packages): Apply OpenType x and y offsets to color fonts

- .github/workflows/luacheck.yml
- package.json
- spec/opentype_spec.lua
- ci(actions): Use Lua 5.4 to run Luacheck
- chore(tooling): Enable direct invocation of busted with limit tests
> Lint using Lua 5.4

- documentation/c03-input.sil
- documentation/c04-useful.sil
- documentation/c05-packages.sil
- documentation/c07-settings.sil
- documentation/c08-language.sil
- documentation/c09-concepts.sil
- documentation/macros.sil
- documentation/sile.sil
- packages/autodoc.lua
- packages/chordmode.lua
- packages/color.lua
- packages/dropcaps.lua
- packages/image.lua
- packages/linespacing.lua
- packages/math.lua
- packages/url.lua
This is a subset of the concerns addressed in #1194 
I have been sitting far too long on it - and my previous attempts ended up being very messy, so it's preferable (I think) to proceed by small steps. Hence the "stage 0" in the PR title.
1. Removal of the `\dots` command in the SILE Manual and package documentations.
- _SILE doesn't do that_... There are plenty of other characters directly in Unicode in the Manual and package documentations (e.g. em-dashes, quotes, etc.), so there's no good reason introducing this only shortcut in the Manual and have package documentations depends on it...
- One may use some LaTeX-[compatibility layer](https://github.com/ctrlcctrlv/sile-texmode) for such things, if one really wants them.
2. Addition of the `autodoc` package documentation (fixed) to the …
> Leverage package documentation and manual (stage 0)

- lua-libraries/lunamark/entities.lua
- lua-libraries/lunamark/reader/markdown.lua
See #669, notably allows `--with-luajit` builds to do more things without tripping over the bogus `require()` that used to be cross-wired to a fork of the correct package with a different module name. Lua 5.3+ doesn't have the same issue because of the internal module of the same name.
> fix(deps): Correct include to work with current LuaRocks packages

- Makefile.am
- configure.ac
Fixes #1353
I had used a bashism that wasn't failing with an error, just not doing the expected job. It didn't matter for system installs to `/usr` (using `./config --prefix /usr`) because Lua has a default path to cover that use case, but it meant our custom path handling for non standard installations wasn't getting processed as expected in `sh` / `dash`. For systems that installed to `/usr/local` we weren't getting a matching `SILE_LIB_DIR` set right.
> Keep configure and install BSD and POSIX friendly

- core/debug-output.lua
- core/font.lua
- core/frame.lua
- core/harfbuzz-shaper.lua
- core/makedeps.lua
- core/measurement.lua
- core/nodefactory.lua
- core/opentype-parser.lua
- core/packagemanager.lua
- core/typesetter.lua
- core/utilities.lua
- languages/ja.lua
- languages/unicode.lua
- packages/autodoc.lua
- packages/bidi.lua
- packages/break-firstfit.lua
- packages/chapterverse.lua
- packages/features.lua
- packages/font-fallback.lua
- packages/grid.lua
- packages/insertions.lua
- packages/math/base-elements.lua
- packages/math/texlike.lua
- packages/math/typesetter.lua
- packages/parallel.lua
- packages/pdfstructure.lua
- packages/ruby.lua
- sile-dev-1.rockspec
The Lua (scare quotes) "stdlib" has some *serious* funny business under the hood. I understand why some bits of it are *convenient* at times, but debugging anything it has touched is a nightmare.
This PR is actually bits extracted from #1065. It was getting really confusing trying to figure out what I broken by changing the class model and what was related to the monkey patch business conflicting with explicit meta methods I was trying to set using Penlight. Separating just the de-monkify bits let me work through all the tests.
By the way in case anything ever `git bisect`s back to here, one way to test if you problem is related to this change or not (especially if you have downsteam code that might have built on the assumption SILE's Lua strings were monkey patched) is to load it …
> Drop std.string.monkey_patch()

- Makefile.am
- flake.lock
- sile-dev-1.rockspec
This still doesn't bring us to parity so `bmake` can be used to build, but it's more steps in the right direction using lessons learned from other (less complex) projects I've successfully setup to build with only BSD native tooling (e.g. [bzip3](https://github.com/kspalaiologos/bzip3)).
> Poke at Nix and BSD build stuff

- configure.ac
The option to not check for dependencies should only apply to *run time* dependencies, not build time ones which should be required all the time to configure.
Closes #1394.
> Address warnings on bootstrap

- classes/base.lua
- classes/bible.lua
- classes/book.lua
- core/sile.lua
- core/typesetter.lua
- documentation/c10-classdesign.sil
- packages/footnotes.lua
- packages/insertions.lua
- packages/masters.lua
- packages/twoside.lua
After breaking changes to the class inheritance system I'm working through some of my projects as tests getting as many of them going with support shims as possible. This gets a few more projects building without needing to port yet—just warnings no errors.
At this point I'm about to start updating CaSILE classes to the new system because they are too complex to shim.
> More followup refactoring after class changes

- classes/bible.lua
- classes/diglot.lua
- classes/docbook.lua
- classes/pecha.lua
- classes/plain.lua
- classes/triglot.lua
- documentation/c12-tricks.sil
- chore(classes): Remove obsolete stashing of classes in globals
- docs(classes): Update egregiously outdated code example
- chore(classes): Make sure all typestter-y bits get called after init
> Minor cleanup to class code, catch some init stuff not in classes not covered by tests

- flake.lock
- flake.nix
Since the relevant PR [has made it through the gauntlet](https://nixpk.gs/pr-tracker.html?pr=177079) and upstream Nix is 0.13.0 all the way we don't need to override anything for the moment. Prior to the v0.14.x release cycle we'll have to introduce this a gain to drop the provision of stdlib, but I'll just keep that in it's own branch (already in #1420).
> Remove unnecessary stuff from Flake

- build-aux/list-dist-files.sh
Fixes this error:
```
! Error loading localizations eo: no localizations for this language at why.sil:2:1: in \languagetable: 0x41510d90
[1] [2]
! No localized message for book-chapter-title-pre found in locale eo at why.sil: in \fluent near 9:1: in \book:sectioningtable: 0x413e6178
```
#1444 is blocked on this being merged.
> fix(build): Make sure `i18n/` dir is actually distributed

- core/base-shaper.lua
- core/settings.lua
- core/units.lua
- languages/ja.lua
- packages/ruby/init.lua
Where it belongs.
This touches on #1245.
This is blocking #1444, somehow (the manual is extremely brittle as all know well):
```
[font-fallback] Glyph あ not found in Gentium Book Basic
! Some glyph(s) not available in any fallback font, run with '-d font-fallback' for more detail at documentation/c08-language.sil:244:1: in \subsection after in \book:subsectionfont
! Unable to measure character at:
documentation/c08-language.sil:244:1: in \subsection after in \book:subsectionfont
documentation/c08-language.sil: in <file> (\)
documentation/c07-settings.sil:51:1: in \includetable: 0x40ddce50
! debug.traceback() did not identify code location
make: *** [Makefile:1451: documentation/sile.pdf] Error 1
make: *** Deleting file 'documentation/sile.pdf'
```
After much ado I discovered that the …
> fix(core): Move the zenkaku width (全角幅; `zw`) unit into core

- classes/jbook.lua
- classes/jplain.lua
- classes/tbook.lua
- classes/tplain.lua
- documentation/c08-language.sil
- tests/bug-1101.sil
- tests/bug-1171.expected
- tests/bug-1171.sil
- tests/bug-244.sil
- tests/bug-524.sil
- tests/bug-525.sil
- tests/bug-915.sil
- tests/bug-926.sil
- tests/jbook.expected
- tests/vertical.sil
As I've been attempting to enforce through my commits, counter to how
@simoncozens did things:
* `tate` and `ruby`: General purpose libraries that *should not be loading
any fonts* or *assuming a Japanese document*.
* `jplain`: The Japanese language class, *may* enforce
`\language[main=ja]` but I didn't for backwards compatibility.
#1452 shows the above backwards compatibility preservation to be ill
advised. Therefore this commit breaks it, closing https://github.com/sile-typesetter/sile/issues/1452.
---
Also adds `\language[main=ja]` to all jplain tests.
Also fixes a test that was returning bad (tests/bug-1171.sil which tests
for regressions to the issue I reported in #1171) because its behavior
is different in the current Noto font w/ja language. I confirm the new
behavior is not worse, …
> fix(classes): Clarify the scopes of `tate` and `jplain`

- core/debug-output.lua
A no-brainer, but seen in passing while generating a debug file (`sile -b debug`) for a test.
```
SILE v0.13.2 (Lua 5.4)
<experiments/background.sil>
Error detected:
./core/debug-output.lua:33: attempt to compare number with nil
stack traceback:
./core/debug-output.lua:33: in upvalue '_round'
./core/debug-output.lua:92: in method 'pushColor'
(...)
```
Turned out my color was in grayscale (`\color[color=220]`) and the debug outputter only knows RGB...
Output kept unchanged for RGB (not to affect existing tests), but fixed for other color schemes (CMYK, Grayscale)
> Non-RGB colors shall not cause an error with the debug outputter

- documentation/c02-gettingstarted.sil
- documentation/c03-input.sil
- documentation/c04-useful.sil
- documentation/c05-packages.sil
- documentation/c06-macroscommands.sil
- documentation/c07-settings.sil
- documentation/c08-language.sil
- documentation/c09-concepts.sil
- documentation/c10-classdesign.sil
- documentation/c11-xmlproc.sil
- documentation/c12-tricks.sil
Here’s a patch that fixes some minor typos I found while going through the SILE manual.
Thanks for your work on SILE, I’m excited to start using it!
> Fix minor typos in the SILE book

- packages/autodoc/init.lua
Closes #1489 
A case overlooked the AST debugging which inspired the autodoc logic:
No idea what it does, but fixes the issue when it occurs.
> The autodoc package could choke on some inputs

- classes/book.lua
- core/sile.lua
- core/tracestack.lua
- packages/autodoc/init.lua
- packages/base.lua
- packages/bidi/init.lua
- packages/break-firstfit/init.lua
- packages/chordmode/init.lua
- packages/converters/init.lua
- packages/counters/init.lua
- packages/date/init.lua
- packages/folio/init.lua
- packages/frametricks/init.lua
- packages/hanmenkyoshi/init.lua
- packages/indexer/init.lua
- packages/infonode/init.lua
- packages/inputfilter/init.lua
- packages/insertions/init.lua
- packages/masters/init.lua
- packages/tableofcontents/init.lua
- packages/textcase/init.lua
- packages/twoside/init.lua
- packages/url/init.lua
This is follow up to #1487 which made all packages into classes inheriting some standardized package functions (and more importantly going forward, scope!) but left some "exports" table stuff around to shim old usage. The old usage is still shimmed here but with a standardized API for new usage going forward.
> Setup and use cleaner API for package exports

- classes/plain.lua
- packages/bidi/init.lua
> Pass document direction info to font shaper by default

- packages/grid/init.lua
- packages/url/init.lua
- Seen in passing, an issue introduced in 0.13
When pdf is supported, `\href[src=uri]{text}` outputs the text in current font and `\href{uri}` delegates the content to `\url`, with additional breakpoints and possibly a different font. The formatting behavior shall be the same when pdf is not supported (i.e., same visual output, whether the hyperlink is active or not).
- From [discussion here](https://github.com/sile-typesetter/sile/pull/1334#issuecomment-1200125592)
Incorrect detection of the backend.
- From [analysis here](https://github.com/sile-typesetter/sile/issues/1174#issuecomment-1173141699)
Ensuring the grid frame hook is ineffective when the grid is off. That might not be a true fix, rather a workaround, but the immediate benefit is that some long-reported vertical issues in the …
> Minor href regression and grid fix

- packages/raiselower/init.lua
Fixes #1504
This is an old function that predates our SILE.length / SILE.measurement
logic and units like `%fh` that are relative to the frame or page. It
was being parsed as a frame dimension, which I assume was just a way to
get user friendly string input and perhaps some expressiveness.
I couldn't actually think of a use case for making this a full frame
string and not accepting our standardized measurement types comes with
lots of downfalls especially in programmatic usage.
I'm not marking this as breaking because in most cases I think the new
behavior will be expected and I doubt the edge cases where they differ
are seeing much use.
> Parse height argument to in raiselower package as measurement

- build-aux/git-version-gen
- packages/chordmode/init.lua
- packages/textcase/init.lua
- sile.in
The internal uppercase() function was exported using the deprecated
export mechanism, but lowercase() and titlecase() were tripping over
their own shim logic.
This fixes the shim logic but also exports them as package functions
which should be used going forward.
> Fixup little issues (mostly with compatibility shims) found in production

- inputters/base.lua
In many cases using `class:registerHook("finish", func)` is probably a better move, but I don't see any reason the pre and postambles should be processed differently and handle different types on inputs.
> Bring postambles to parity with preambles

- documentation/c12-tricks.sil
- outputters/debug.lua
- outputters/libtexpdf.lua
- packages/image/init.lua
- src/imagebbox.c
- src/justenoughlibtexpdf.c
Three commits touching quite the same bits of code:
* This is the required C support for the possible enhancements evoked in #1346
Outputters using the libtexpdf backend to compute an image size, such as "debug" and "libtexpdf", also return, as additional results on the `getImageSize()` method, the image resolutions in dots (pixels) per inch.
This may be used by packages/classes to check images have an appropriate (e.g. print) quality regardless of their claimed size (in pt), or to downsize too resolved images, etc. - but that is a separate concern ; this PR just offers the tooling.
Ex. with `documentation/gutenberg.png` (200 x 243 pixels) unscaled = 144pt x 174.96 pt at resolution 100 dpi x100 dpi.
N.B. Libtexpdf's density is in pt/in. It's converted back to dpi, here, as it is more …
> Image resolution and PDF page selection with libtexpdf backend

- packages/base.lua
Some packages may bundle non-Lua resources (images, SIL, XML, etc).
Given the packages themselves are loaded with Lua's module loader using
`package.path` it can be tricky to then find the other assets. Rather
than letting ever package author re-invent this wheel this just gives
a little API that can be used any time later to recover the path where
the package was loaded from.
> Add API so packages know their basedir and can load relative assets

- src/justenoughlibtexpdf.c
The function is non-void, but it doesn't return anything in the end. Without this, gcc complains with a "return reaches end of non-void function" warning, which is treated as an error on certain Linux distros such as openSUSE.
> fix(justenoughlibtexpdf): pdf_metadata

- README.md
> docs(readme): `a a`→`a`

- Makefile.am
> Avoid mktemp during build, breaks opensuse packaging

- documentation/c02-gettingstarted.sil
- documentation/c05-packages.sil
- documentation/c08-language.sil
- documentation/c10-classdesign.sil
- documentation/c11-xmlproc.sil
- documentation/developers.sil
The manual should thrive for nice typography, to be convincing for casual readers ;)
> docs(manual): Improve some bullet lists and apostrophes

- documentation/c04-useful.sil
And remove the sentence about boldface being a bad practice.
There are legit use cases for it in some fields.
See last checkbox in #1351
> docs(manual): Mention `\strong` command as shorcut for weight 700

- packages/math/texlike.lua
I noticed a strange behaviour when typesetting math tables with 11 rows or more:
```
\begin[class=plain]{document}
\script[src=packages/math]
\math[mode=display]{
\table{
0 & 0 & 0 \\
1 & 1 & 1 \\
2 & 2 & 2 \\
3 & 3 & 3 \\
4 & 4 & 4 \\
5 & 5 & 5 \\
6 & 6 & 6 \\
7 & 7 & 7 \\
8 & 8 & 8 \\
9 & 9 & 9 \\
10 & 10 & 10 \\
}
}
```
Some of the rows are permuted non-deterministically, depending on the execution… it turns out that I make the mistake of relying on the iteration order of `pairs()` when compiling to MathML. This PR fixes it.
> fix(math): Fix insertion order of MathML children

- documentation/c03-input.sil
It's confusing to me that it lists a4, b5 etc followed by the word also then a list that... includes those aforementioned A/B/C ISO sizes.
> Paper size present documentation

- core/font.lua
- documentation/c03-input.sil
- languages/und.lua
It said that you turned off the latin hyphenation but the rendered text in the manual as downloadable from your homepage does have that latin text with some hyphens.
> Remove misleading text about latin hyphenation

- inputters/base.lua
> Permit content outside of the document note, e.g. comments or blanks

- documentation/c07-settings.sil
- documentation/sile.sil
Closes #1617 
- One global setting to allow more stretching tolerance on bad lines (preferring underfull ones to overfull ones)
- The second commit addresses a bunch of small issues in the "c07" (SILE settings) chapter: removal of some manually inserted breaks, use of the autodoc features (which add some extra breakpoints), proper scoping of a parfillskip change.
> Improved line breaks in the SILE Manual

- documentation/c08-language.sil
Seen in passing.
@ctrlcctrlv Can you double check this is indeed a typo? Seems to me "chapter" is "ĉapitro" in Esperanto and that it was the intended example here, no?
> Small typo in Esperanto language section

- documentation/c02-gettingstarted.sil
- inputters/base.lua
- inputters/sil.lua
- inputters/sil_spec.lua
- inputters/xml.lua
- inputters/xml_spec.lua
- packages/autodoc/init.lua
- packages/chordmode/init.lua
- packages/inputfilter/init.lua
- packages/url/init.lua
Closes #1637
Please do sanity check me on this one @Omikhleia. This completely moves the cheese around but I think it makes more sense overall and likely fixes your use case of a different inputter. I moved the check for leading/trailing junk that was specific to SIL to the SIL inputter. I also reworked the check for a document to potentially wrap loose leaves which should make document fragments more viable with no top level tags. It won't necessarily sniff but it should parse if asked to explicitly. In the process the expecations about top level tags changed, so XML no longer has to add an extra level of nesting it just runs with whatever the top level is. Of course this changed all the unit test expecations, but the change seems way saner than the original.
Am I breaking it or fixing …
> Cleanup inputter AST nesting expectations

- packages/bibtex/init.lua
Really tiny code change to make the bibtex packe work with LaTeX-style citations.
Before, `\cite{abc}` errored with:
`Using code at: ./packages/bibtex/init.lua:98: attempt to concatenate a table value (field 'key')`
Unsure if this is the right approach to fix this, so I am open to further suggestions.
> bibtex package: Fix \cite{key}

- src/justenoughharfbuzz.c
Use `hb_shape_full()` instead of fiddling with shape planes as `hb_shape_plan_create_cached()` ignores variations set on the font (one needs to use `hb_shape_plan_create_cached2()`), but `hb_shape_full()` does all that for us and there is no need to re-implement it.
Fixes https://github.com/sile-typesetter/sile/issues/1265
> fix(shaper): Respect variations when shaping (#1265)

- src/justenoughharfbuzz.c
Follow up to #1662 with patch mentioned in #1265.
> Correct font-variants using opsz axis

- .github/workflows/coverage.yml
- .luacov
It turns out I got coverage reporting working again lately but it was only calculating coverage based on the files that actually reported some coverage. Files that didn't get loaded at all during testing didn't get included in the total. This should give us a better idea of where we are at percentage wise but also the reports detail what files aren't being tested at all and hence need tests to be added.
> Correct coverage stats

- packages/tableofcontents/init.lua
Several small points:
- Kerns were overlooked and ignored with a warning.
- Kerns and glues were always converted to a space, but "small" enough kerns/glues should rather be ignored. E.g. using a small adjustement kern for pseudo-italic correction shouldn't result in a space, although the logic cannot be anything else but heuristic.
- Resulting string was not trimmed, and could contain repeated internal spaces.
N.B. back-porting this from a bunch of pending fixes I have for my resilient.tableofcontents too.
(I really think the nodeToText function should be moved into the utilities, but this is a separate topic.)
> fix(packages): Text conversion in bookmarks has spacing issues

- classes/base.lua
- core/utilities.lua
Two little proposals:
`SU.boolean` now errors on anything that is not true, false, "true", "false", "yes", "no" and nil --> IMHO, it helps avoid typos to remain unnoticed and possibly evaluated to the default value.
- `SU.cast` now warns on `SU.cast("integer", somefloatvalue)` --> IMHO it helps reporting where the code really expected an integer.
- But it does not warn, e.g. on "integer or number" (this was implied by the previous code, though it's not that useful!)
- And it only warns, but does not error, as it's hard to be sure we wouldn't break some packages (and what is the actual issue there, whether integer was really expected or not).
And following upon that, an actual type consistency fix (`current.hangIndent` vs. `linebreak.hangIndent`). It doesn't mean there aren't others, they …
> Enforce slightly better type casts in utilities

- classes/base.lua
Closes #1361 
We sat too long without addressing this problem, but it's not acceptable to still fail justifying a text when a font-relative parindent is used (e.g. 1.25em).
Most typographers actually recommend using such a relative parindent, rather than the current default fixed 20pt setting...[^1]
E.g. Lacroux, _Orthotypographie_, discussing Lefevre (1855) and the traditional value of 1em (my quick and approximate translation from French):
> In “ordinary” or balanced compositions (font size, letter spacing and line spacing all well suited for justification, use
> of a "reasonable" font family), the traditional indent of one em-space seems appropriate to me. However, typographic
> art is pleasing in the fact that it combines rigid conventions and the freedom to cheerfully escape them. …
> Avoid justification issues with relative parindent

- packages/scalebox/init.lua
Closes #1178
EDIT: Also Closes #1035 (see comments below)
Box re-scaling via PDF transformation matrix:
`\scalebox[xratio=<number>, yratio=<number>]{<content>}`
_Rationale_
Both @ctrlcctrlv and @alerque in the above-mentioned issue said it should be proposed to the core distribution... So here it is, basic logic extracted from textsubsuper.sile and re-vamped as as standalone package.
_Caveats_
- It's only tested (see below) in LTR writing direction: Checking RTL and vertical writing directions is left as an exercise to readers who know how to use these.
- It's using the "hbox stealing trick": When/if #1702 makes it, it is left as an exercise to adapt the code so that migrating contents are honored.
- It is also left as an exercise where to include the package documentation in the manual. …
> feat(packages): New scalebox package for arbitrary box re-scaling

- core/utilities.lua
- documentation/c10-classdesign.sil
- packages/tableofcontents/init.lua
So as to avoid reporting a ToC change when ToC entries contain sub-content commands and the text before changed without affecting the actual entry (same title, landing on same page)
Close #1732
> Strip content position in ToC entries

- documentation/c10-classdesign.sil
- documentation/c12-tricks.sil
Closes #1693 
Note: it's a "minimal" fix for the reported issue. Section "10.3 Exports" is still outdated, and hooks aren't explained.
> docs: Update manual for deprecated uses of SILE.registerCommand()

- documentation/c01-whatis.sil
Following discussion #1729:
A proposal to rephrase some of the sentences in the manual's introduction, to avoid unwanted comparisons and judgement of values.
I'm not that good at that game - feel free to comment/improve on the matter, @jslabovitz and others!
> docs(manual): Reword introductory sections in a more neutral way

- core/nodefactory.lua
Closes #1721 
`SILE.nodefactory.hfillglue()` = `0pt plus infinity` (as before)
`SILE.nodefactory.hfillglue("20pt")` = `20pt plus infinity` (new - rather than `20pt`).
Likewise for hssglue, vfillglue, vssglue.
Also added an unrelated comment on `SILE.nodefactory.kern` and `SILE.nodefactory.vkern`, there's a tricky discrepancy there, that we may want to address at some point...
> Support initializing fill glues with a width

- documentation/c04-useful.sil
- documentation/c09-concepts.sil
- languages/fr.lua
Close #1267 (well, the last unaddressed checkbox)
In Chapter 9 (The Nitty Gritty):
- Add "Measurements and lengths" new section (moving content from below and extending it)
- Slightly refactor "Boxes, glue, and penalties" section as appropriate.
- Move "Kerns" (sub)section closer to the above (sounds more logical, as of introducing concept progressively)
- Split "The typesetter" section apart below these
In all the above, add a bit more of autodoc's magic here and there.
> docs(manual): Add section on measurements and lengths

- core/makedeps.lua
- outputters/base.lua
- outputters/cairo.lua
- outputters/debug.lua
- outputters/dummy.lua
- outputters/libtexpdf.lua
- outputters/podofo.lua
- outputters/text.lua
Both SILE's own regression suite and CaSILE have happily used this broken feature for a long time because it always specifies --output explicitly, but the --makedeps feature has been broken for a long time because it couldn't derive the correct filename and was trying to
concatenate nil.
(Found while porting CLI to Rust).
> Fix --makedeps to play along without explicit --output

- documentation/c10-classdesign.sil
- packages/autodoc/init.lua
- packages/base.lua
- packages/svg/init.lua
Back from a few days off away from the internet, here is a proposal to address (a part) of #1465
The very first commit adds `self:registerRawHandler()` to the package API, similar to what was done for commands in 4875972c, for the rationale explained in its commit log.
The subsequent commits is a rewrite of the manual's "c10" chapter:
- Change from "Designing Basic Class Files" to "Designing Packages & Classes"
- Change introductory text:
- Explain the difference between a class and a package (a well-known concept for (La)TeX users, but let's target a general audience)
- Introduce the Penlight OOP framework briefly. We didn't mention it earlier, in the subsequent sections. Here, users will see `pl.class()` constructs, so it's more than time...
- Add a first section covering packages first …
> Rewriting of the manual's chapter 10 (designing packages and classes)

- .cirrus.yml
- .github/workflows/coverage.yml
- .github/workflows/test.yml
- Makefile.am
- configure.ac
- flake.lock
- flake.nix
- libtexpdf.git-rev
After experimenting with building projects that depend on git submodules, I reached the conclusion that this is the most comfortable way of handling such dependencies. You may like this approach since updating `libtexpdf` for the flakes will only require:
```
nix flake update
```
and the above will also update libtexpdf to it's latest version. Using a specific version of libtexpdf is possible using:
```
nix build --override-input libtexpdf-src "github:sile-typesetter/libtexpdf/my_feature_branch"
```
You can also do the above while disabling changing the `flake.lock` file:
```
nix build --override-input libtexpdf-src "github:sile-typesetter/libtexpdf/my_feature_branch" --no-write-lock-file
```
> ci(build): Get libtexpdf into build using flake inputs

- src/justenoughharfbuzz.c
This bug has been around forever. We've been allocating 1 space on the stack then pushing 8-10 items to it. LuaJIT automatically adjusts. PUC Lua has been using undefined behaviour and just dealing with the stack overflow as long as it didn't get clobbered by anything else. However compiling Lua in debug mode reveals the stack overflow. I ran into this while wrapping SILE in the Rust CLI with embeded mlua interpreter, but it affects all builds so this fix deserves to go in earlier rather than later.
With special thanks to @khvzak for the help debugging.
> Avoid stack overflow in Harfbuzz module

- packages/converters/init.lua
Closes #1795
Due an inadvertently inverted check.
Also if wasn't resolving the source file name so could not work with relative paths that would have been acceptable for a resource not needing conversion.
The hardest thing was testing that package... and refraining rewriting it wholly :rofl:
> fix(packages): Converters package no longer worked after 0.13.0

- documentation/c01-whatis.sil
- documentation/c02-gettingstarted.sil
- documentation/c03-input.sil
This PR is because I've been a bit frustrated with chatter abut Typst and folks comparing it to SILE without having any idea what they are talking about. Don't get me wrong Typst has done some things right and other things well. Of course it also does some things poorly or not at all. Sometimes it just makes significantly different design choices and that's fine (e.g. sandboxing everything so documents are "safe" and cannot read the network or write to files at render time vs. SILE that just lets you have a full featured programming language ecosystem and treats documents as unsafe programs).
On the other hand it feels bad to be put down for things that just aren't true. Our documentation is a contributing factor to that confusion.
One of the most egregious issues brought up several times …
> Try to clarify that SILE doesn't require a custom input language

- documentation/c02-gettingstarted.sil
- documentation/c03-input.sil
- documentation/c04-useful.sil
- documentation/c06-macroscommands.sil
- documentation/c07-settings.sil
- documentation/c08-language.sil
- documentation/c09-concepts.sil
- documentation/c10-classdesign.sil
- documentation/c11-xmlproc.sil
- documentation/c12-tricks.sil
- documentation/sile.sil
- packages/autodoc/init.lua
- packages/folio/init.lua
- packages/specimen/init.lua
Proposed changes:
- Add `\autodoc:class` for styling class names (similar to `\autodoc:package`)
- Use it where appropriate
- Also fix a few missing or erroneous package names
- Enable autodoc color highlighting[^1]
- Expand description of horizontal and vertical spacing = Closes #577 
- Slightly rephrase the explanations on `\par` vs. `leaveHmode()` = Closes #868
Here I mostly removed a weird sentence, slightly changed the formulation and split the dense explanation into shorter paragraphs. Most of the important things were already stated, IMHO, so perhaps harder to find and read.
[^1]: That may place us in situations where #1659 occurs, but everything comes at a cost, heh...
> Various docs changes

- README.md
Still three packages left, but many have been added to Fedora. Only builds for Fedora 38 and later due to `harfbuzz-devel >= 6.0.0`
> Updated Fedora section in README.md

- classes/base.lua
- core/makedeps.lua
- core/sile.lua
- documentation/c10-classdesign.sil
- outputters/base.lua
- packages/cropmarks/init.lua
- packages/tableofcontents/init.lua
Closes #1833.
As far as SILE itself is concerned this shouldn't be noticed, but that's not to say documents or other project code that generates files and assumes that `masterFilename` is a basename not a file name won't be affected. I had in mind to put this in the next breaking release just to be safe, but given the current situation I'm not sure adding more hacks to work around this silly problem in the short term knowing we want to fix it properly anyway makes sense either.
This will break CaSILE but I'll fix that. I don't know if any other 3rd party extensions will be affected.
@Omikhleia does this change make sense to you?
> Make masterFilename what it says on the tin

- core/utilities.lua
- packages/tableofcontents/init.lua
> Cleanup warning outputs

- core/sile.lua
> Fix SILE.require() to generate normal Lua module specs

- README.md
Closes #717
Remove the japanese google group from the README
- No one from the SILE organization has access to it
- It's not an "open" group and we can't tell if it stopped being active, but there's no known way to register to it...
In #717 @alerque notes:
> Just FYI at one point there was even a complete SILE manual translated to Japanese (when it was 80-90 pages if I recall). I don't know if there is still lots of active use in an isolated subculture there, but at one time at least there was. Until we poll somebody from that group I don't think we should impose time limits on erasing notes about their existence.
The japanese manual is here: https://github.com/shirat74/SILE-doc_ja
- No change for 6+ years
- Thus still in version 0.9.5
- Author never answered …
> docs(readme): Remove unreachable closed japanese google group

- .github/workflows/test.yml
- Makefile-luarocks
- Makefile.am
- packages/footnotes/init.lua
- src/justenoughharfbuzz.c
Fixes #1886. Or should, currectly it just helps debug it...
> Get Lua 5.1 CI working again

- core/sile.lua
- packages/bibtex/init.lua
> Silence resolveFile()

- configure.ac
- sile.in
This should fix CaSILE so it can be released again depending on the current SILE version instead of only working with the development branch. It now sets multiple SILE_PATH segments: for itself, for the project, for any other toolkit packages being added, etc.. That made it dependent on the unrleased SILE development branch, which prohibits it being released. As that is the only change it was dependent on, the change is not breaking, and it is easy to backport I figured why not…
> Backport a couple things from develop to master

- core/cli.lua
- core/deprecations.lua
- core/pagebuilder.lua
- core/settings.lua
- core/sile.lua
- core/typesetter.lua
- packages/balanced-frames/init.lua
- packages/bibtex/init.lua
- packages/counters/init.lua
- packages/infonode/init.lua
- packages/masters/init.lua
- packages/rules/init.lua
- packages/twoside/init.lua
Since the version isn't set to v0.15.0 yet it wasn't apparent we were still using deprecated APIs internally.
> Remove code soon to be inaccessable because of deprecations

- Makefile-fonts
- packages/ruby/init.lua
- tests/bug-1047.expected
- tests/bug-1047.sil
- tests/bug-524.expected
- tests/bug-524.sil
- tests/bug-525.expected
- tests/bug-525.sil
- tests/bug-926.expected
- tests/bug-926.sil
Closes #1047
I wasn't sure if the font size was something we still needed to set to a smaller size relative to the base font or if the +tate feature should also produce approriately sized glyphs.
> Use OpenType +ruby feature for ruby, toggle with setting

- .luacheckrc
- core/cli.lua
- core/deprecations.lua
- core/packagemanager.lua
- core/sile.lua
- core/utilities.lua
- outputters/debug.lua
- outputters/text.lua
- packages/base.lua
- packages/bibtex/bibliography.lua
- packages/math/base-elements.lua
- packages/math/texlike.lua
We don't technically have to be this strict since compat53 shims a lot of things for us, but this will keep us out of trouble better. For example `table.unpack()` is shimmed, but the shim is not nil safe so better to use `pl.utils.unpack` anyway.
> Fix linter to be stricter 5.1

- build-aux/pkg.nix
- justenough/macfonts.m
> Touchup Mac builds and Nix flake

- core/parserbits.lua
- core/sile.lua
- inputters/sil-epnf.lua
- inputters/sil.lua
- inputters/sil_spec.lua
- sil.abnf
I've been trying to use the ABNF to automatically generate SIL parsers in other languages and this has turned up a few issues with it. In fixing those I checked the actual SIL parser as a reference and discovered some bugs there too. For example values not being trimmed and quite unexpectedly allowing unescaped quotes if they are not balanced and more. This is ongoing work on both the ABNF spec and the LPEG grammar.
> Keep working on ABNF and fix actual SIL parser to match

- classes/base.lua
- core/sile.lua
- inputters/base.lua
See #1974, probably more things to address yet but this is the big one.
> Store instantiated packages not just module source

- packages/frametricks/init.lua
The user should have the option of disabling the balancing when calling `makecolumns`. For example, this just happened to me right now, using the default `makecolumns`:
But I wanted their bottom to be the same as the original frame, which I got after setting balancing to false:
> Balancing in command makecolums set as an option

- core/nodefactory.lua
- typesetters/base.lua
The discretionary nodes still had some weird logic to determine whether a prebreak or a postbreak must be shown: it was doing it _at page output time_ by re-analyzing the line content and making clever guesses (skipping glues etc. until reaching its own presence here...) with a strong assumption on how lines are composed.
This extra weirdness of re-parsing the line:
- Doesn't make sense as line ratios etc. are already computed _at typesetting time_ (more precisely at line breaking), so there's no benefit to be expected, so it had some code smell...
- We already have the necessary information at an earlier point...
- It doesn't play nice with #1977 which re-boxes elements...
While we fixed and improved it in earlier releases, the typesetter's `computeLineRatio` still had some code smell …
> Simplify discretionary logic and line ratio computation

- packages/raiselower/init.lua
This was present since the very first commit of the raiselower package, but we do not have any use of such a thing anywhere else in the code base.
I think we can safely remove it...
I noticed it a while back, and remembered it when checking whether this raise/lower commands should use the new liners (the answer that question would be "no", it doesn't seem to me this case meets the criteria).
Another question, then should come its own issue shortly afterwards,.. I can tease it here, though:
Regarding the signature of `ouputYourself` methods, why do we still need the typesetter at output time? It's job ought to be finished then! All we seem to need is... the frame. (I'm still checking the code to check if there is any counter-argument).
> refactor(packages): Remove unused typesetter-scoped cursor tracking

- core/settings.lua
- core/settings_spec.lua
c.f. https://github.com/sile-typesetter/sile/issues/1963#issuecomment-1925228811
After discussion on the above issue I looked and found 3 different places I had monkey-patched a callback system into settings for various reasons. Looking over my own past hacks I think this feature would have made all of them better.
> Add active hook system to settings

- documentation/c02-gettingstarted.sil
- documentation/c03-input.sil
Chapter c02
- Corrected apostrophes from straight to curly.
- Reorganized content flow to enhance coherence
- Previously, the sequence oscillated between topics.
We had: Setting up an editor (not the first thing I'd would have put an accent on), typing a SILE document (but we can't do anything with it yet), installing SILE, back to the SILE document (repetitive) for running instructions. 
- Now, it follows a more logical order:
1. Installing SILE (straight on topic, we _want_ it installed!).
2. Setting up an editor (ok, let's finish setting up things...)
3. Typing a SILE document and executing it (yay! fun things all grouped)
Chapter c03
- Corrected apostrophes, quotes and some typos.
- Adopted a more formal tone (and avoid comparing with past versions)
- Rewrote most of the introductory …
> Manual: Reorganize Chapters 2 and 3

- documentation/c05-packages.sil
A.k.a. "Good maturity"
The main concern here is that some constructs previously used an hbox, and could not span multiples lines.
They now use "liners" supporting this use case.
Other refactors also made the code much better.
That is, features currently on develop --> for 0.15.0 as well.
Note: The same would be true for the **pdf** packages, but the latter has other concerns too (naming, scope, outputter interfacing) which in my opinion mandate it being left as "medium" (a.k.a. "Usable with limitations")
> Manual: Bump url and rules to high status

- documentation/c04-useful.sil
Closes #1854 
Set to 0.15 because written based on current "develop" documentation, which already addresses some of the points from the original issue.
> Manual: Explain raw handlers and reserved SIL keywords

- README.md
- default.nix
- documentation/c02-gettingstarted.sil
- flake.nix
- shell.nix
Context: https://discourse.nixos.org/t/wiki-nixos-org-is-now-live/42570
> README: change to official NixOS wiki

- packages/simpletable/init.lua
This PR fixes the `simpletable` package documentation.
But I would also ask your opinion on the following: today this package must be called from a class, and calling it from a document raises an error. I think that this behavior is not intentional, given the tests present in line 15:
`   if type(options) ~= "table" or pl.tablex.size(options) <= 3 then`
When `simpletable` is called from a document, it receives a table as `options`, and its size is 12. Thus, the check in line 15 fails.
What do you think, to change the second test to
`   if type(options) ~= "table" or pl.tablex.size(options) ~= 3 then`
?
> Fix spelling mistakes in simpletable package documentation

- packages/math/init.lua
- packages/math/typesetter.lua
- tests/feat-math-display-numbered.expected
- tests/feat-math-display-numbered.sil
- tests/feat-math-display-unnumbered.expected
- tests/feat-math-display-unnumbered.sil
Something is better than nothing -- This is a curated re-implementation of @leorosa 's #1821 taking into account all comments there.
- `\math[mode=display]{...}` works as before
- `\math[mode=display, numbered=true]{...}` uses counter "equation" for numbering
- `\math[mode=display, counter=id]{...}` uses counter `id` for numbering
- `\math[mode=display, number=xxx]{...}` uses direct value `xxx` as number, would the use want any unusual equation "naming" which can't be achieved by a regular counter
Two test files are also included.
(While the package code does not depend on it, tests uses the blockquote environment for checking margin stkips are honored, hence the 0.15 milestone label).
STILL TO DO: Generate the text expectations (my fresh install of SILE using the nix flake for the …
> Display math numbering

- languages/pt.lua
This PR follows the problem in #2001... And yes, only three syllables, that's all when it comes to the pairs like ó/ô for PT-PT and PT-BR, respectively. Regarding to further differences between these two branches of Portuguese, they aren't related to anything this file has to do... And since the 1990 we have this Agreement among all the Lusophone countries, according to which:
> As for divergent spellings such as *anónimo* and *anônimo*, facto and fato, both will be considered legitimate, according to the dialect of the author or person being transcribed.[^*]
[^*]: (https://en.wikipedia.org/wiki/Portuguese_Language_Orthographic_Agreement_of_1990)
> Add three missing syllables of Brazilian Portuguese

- classes/base.lua
- inputters/base.lua
Fixes #2083, although I'm unsure if this is actually a fundamental improvement or if it just makes a bigger mess of variable scopes. Catching the error and suggesting preambels might be a better route.
> Make document state available during class's post init

- outputters/text.lua
Pun intended.
Looking at you Fedora, GitHub, and browser based editors.
c.f. https://artifacts.dev.testing-farm.io/0eb6559c-43aa-43fd-a0f7-b653dfd5013e/
c.f. https://bugzilla.redhat.com/show_bug.cgi?id=2149698#c37
> Escape Unicode so over-zealous code linters don't flip out

- core/utilities/sorting.lua
- justenough/justenoughicu.c
- spec/utilities_spec.lua
I noticed when working on #2082 : Our `SU.collatedSort()` works on list of strings only:
```lua
local names = {"Charlie", "Bob", "Alice"}
SU.collatedSort(names)
--  gives: {"Alice", "Bob", "Charlie"}
```
My own bad at the time (#1632)... but we can't use it to sort structured (key-value) tables with a comparison callback, as one would do with `table.sort()`.
Of course there's a workaround, but it's a bit annoying (comparing for string equality, then performing a second ICU comparison for ordering)
So this PR is a proposal for supporting it, as:
```lua
-- Sort by age then name
local namesAndAges = { {name="Charlie", age=25}, {name="Bob", age=30}, {name="Alice", age=25} }
SU.collatedSort(namesAndAges, nil, function (a, b, stringCompare)
if a.age < b.age then return true end
if a.age > b.age …
```
> Extend SU.collatedSort for complex table sorting

- src/cli.rs
- src/lib.rs
> Fix handling of --option flag in Rust CLI

- README.md
SILE is now included in Fedora Linux
> Updated Fedora Linux in README.md

- packages/math/texlike.lua
Movin' forward...
One needs [incentives](https://en.wikipedia.org/wiki/Laplace%27s_method#Formal_statement_and_proof), so the target should be:[^1]
Closes #2131 
Closes #2130 
(The latter being... a side effect ;)
[^1]: This target also requires `\text` support... #2140
> TeX-math limits and other commands behaving as big ops

- packages/math/base-elements.lua
- packages/math/texlike.lua
- packages/math/typesetter.lua
On the quest to tick another box in #2138
- MathML `<mphantom>`: MathML Core encourages the use of CSS for styling, but of course we don't have that. It's still a valid "full MathML" construct though.
References:
- https://w3c.github.io/mathml-core/#making-sub-expressions-invisible-mphantom
- https://www.w3.org/TR/mathml4/#presm_mphantom
- TeX/LaTeX `\phantom`, `\hphantom` and `vphantom` are no-brain implementations, with a small special extra attribute to MathML (`<mphantom>` only corresponds to `\phantom`).
References:
- https://latexref.xyz/_005cphantom-_0026-_005cvphantom-_0026-_005chphantom.html
**Note**: MathML has some extra considerations such as the "form" of operators in a phantom formula (e.g. `<mo form="infix">+</mo> ...`  - This is not addressed here, and would require a more …
> Support MathML mphantom and TeX-like phantom, hphantom, vphantom

- packages/math/base-elements.lua
- packages/math/texlike.lua
- packages/math/typesetter.lua
- packages/math/unicode-mathvariants.lua
- tests/bug-1495-inline-math-layout.expected
- tests/feat-math-display-numbered.expected
- tests/feat-math-display-unnumbered.expected
- tests/math-bigops.expected
- tests/math-macros.expected
- tests/math-stretchy.expected
- tests/math-stretchy.xml
- tests/math-subsup.expected
Closes #2146
~~WARNING: Currently on top of a raw merge of various branches.~~
> Fix math mathvariants

- inputters/lua.lua
- packages/tableofcontents/init.lua
- **chore(core): Add chunk names to side-loaded code**
- **chore(core): Limit side-loaded content to text only when not expecting binary**
> Add chunk names to load code sideloading

- packages/math/base-elements.lua
- packages/math/texlike.lua
- packages/math/unicode-symbols.lua
_One can't make an omelette without breaking eggs._
I was so focused when I fixed a condition on moveable limits (which I marked as a workaround)... that I didn't realize I had broken my nice previous support for limit-like operators at that point or just earlier...
So I guess it's time to remove the workaround and move forward supporting the `movablelimits` attribute properly.
Note: It's still not perfect -- I know there's still a lot to refactor in the unicode symbols and atom types... But this one takes time to be done properly: merging our symbol definitions with the MathML "operator dictionary" extracted from the Unicode data files...
> feat(math): Support MathML movablelimits attribute

- packages/math/texlike.lua
- packages/math/unicode-mathvariants.lua
On greek uppercase, the theta variant and the nabla:
On greek lowercase, 
(I double-checked the codepoints, but Libertinus Math seems indeed to lack the bold sans serif and bold sans serif italic for all these extra greek variants, but the "variant theta symbol")
It also "extends" the use of italic for these lowercase characters when used alone (as a one-character `<mi`>), 'cause one expects:
``\def{left}{}
\def{right}{}
\left(
\sum_{j=1}^4 \epsilon^j \phi_j +
\left(
\sum_{k=5}^8 \epsilon^k 
\right) \phi_5
\right)
+ \sum_{i=2}^8 g_i
\left(
\sum_{j=1}^4 \epsilon^j \phi_j +
\left(
\sum_{k=5}^8 \epsilon^k 
\right) \phi_5
\right)^i``
(Compare with (La)TeX https://tex.stackexchange.com/a/116269)
> feat(math): Support mathvariant on special extra greek characters

- packages/math/init.lua
- packages/math/typesetter.lua
See #2160.
This is a conservative workaround.
Introducing the predisplay/postdisplay penalties is the right thing to do, but a more general solution to the full issue requires a more subtle handling of in-paragraph display math equations, which is not considered here.
> fix(math): Avoid page breaks before display math equations

- packages/math/base-elements.lua
- packages/math/typesetter.lua
Bevelled fractions (also known as skewed or diagonal fractions) are displayed with a slanted line (slash) instead of a horizontal bar.
Although this feature is still included in MathML4, it has been [excluded from the MathML Core](https://github.com/w3c/mathml/issues/29#issuecomment-2276354003) specifications.
As a result, most browsers are unlikely to support bevelled fractions...
But SILE is not a browser -- so it has the freedom to implement a broader standard! :cake: 
As stated in the in-code comments, though, MathML4 does not exactly specify how to compute the layout, and the related OpenType math parameters are, at best, unclear[^1] -- and not pleasant looking; moreover there's no clear distinction for display / cramped / text modes... :cactus: 
So I went for my own interpretation, …
> feat(math): Support MathML bevelled fractions

- packages/math/typesetter.lua
Closes #2172 
As noted in the issue, the use case is not entirely clear...
Here I went for pure suppression of these operators, while respecting lspace/rspace attributes if non-zero: at least, the test cases I've checked clearly look better, and we then are also closer to what MathJax outputs for the same MathML. 
So it does seem to me that's a reasonable move...
> fix(math): Suppress invisible operators in MathML

- packages/math/unicode-mathvariants.lua
Despite having built a table to check all these, I overlooked those two where I had a mere copy & paste issue from the wrong mapping table.
> fix(math): Erroneous capital H and I in fraktur variant

- packages/math/base-elements.lua
- packages/math/texlike.lua
- tests/math-underset-overset.expected
- tests/math-underset-overset.sil
Closes #2133
Did I say that my remaining math tasks would be slightly controversial? 
Well, this one isn't really, provides a good TeX-like feature and fixes a spacing weirdness, along with a nice test.
_Yet,_ the code has some smell. Not really what I added, the smell was just here unrevealed, and now we are all eyes on it.
I've spent literally hours to try finding the root cause, with no result, so I went for the most minimal things I could do to make it work without breaking something else (esp. MathML tables)... I cannot spent more efforts here on such a "small" topic, while "accents" are still awaiting and the last big missing block in our math experience...
Still, I'd advocate for the PR to be accepted, it does it's job supporting a missing feature nicely, and maybe one day someone …
> Math overset/underset and munder/mover spacing

- build-aux/ax_lua_require.m4
- build-aux/pkg.nix
- flake.lock
Hey @doronbehar, my attempt to port the upstream packaging changes to the sile derivation to the flake here did not go quite as planned. It builds and runs, but it doesn't *work* as it should as evidenced by the fact that I can delete stuff in the `luaPackages` array and the build doesn't fail the configure stage where it should be detecting dependencies. That tells me the upstream package one is being used, not the locally defined one. I couldn't figue our the Nix language incantation to override the array in the passthru table and use it in the luaEnv at the same time.
> Sync Flake with nix derivation changes for easier extension of available Lua modules

- .luacheckrc
- Cargo.lock
- Cargo.toml
- core/sile.lua
- core/utilities/init.lua
- outputters/libtexpdf.lua
- rusile.rockspec.in
- src/bin/sile.rs
- src/embed.rs.in
- src/lib.rs
- **chore(deps): Depend on snafu for more robust error handling**
- **feat(cli): Output runtime errors pretty-printed for readability**
- **refactor(cli): Bubble-up more error conditions**
- **fix(outputters): Don't attempt to create output if we error before processing even starts**
- **fix(core): Avoid internal error when also erroring due to user provided content errors**
- **chore(tooling): Drop now obsolete lint exception for non-standard globals**
- **style(tooling): Restyle Lua code with stylua**
> Properly format errors, avoid erroring after already triggering an error

- packages/math/atoms.lua
- packages/math/base-elements.lua
- packages/math/init.lua
- packages/math/texlike.lua
- packages/math/typesetter.lua
- packages/math/unicode-accents.lua
- packages/math/unicode-symbols.lua
Closes #2150
**Description**
**1**. So let's first be positive, regarding what this PR brings:
- MathML accent/accentunder on mover/munder/munderover elements
- Many top and bottom accents "quite well placed" (no longer floating off the formula): accents, arrows, etc.
- Proper syntax support for these in TeX-like math syntax
- TeX-like "variant" limits (varlimsup, varliminf, varprojlim, varinjlim)
- Horizontal braces, brackets and parentheses, with appropriate TeX math support (over/underbrace, over/underbracket, over/underparen)
That's not too bad, from a user point of view.
IMHO, we wouldn't fare long without accents, and this is exactly what this PR solves on the surface, leaving room for further improvements (see below).
**2.** The implementation is _slightly_ more controversial:
- …
> feat(math): Minimal support for accents in MathML and TeX-like commands

- inputters/xml.lua
- inputters/xml_spec.lua
See discussion in #1837, not actual issue but a side quest.
> Cleanup XML input before processing

- core/utilities/init.lua
- outputters/base.lua
- outputters/debug.lua
- outputters/libtexpdf.lua
- outputters/text.lua
In an attempt to not throw errors when closing a PDF we couldn't actually start, I busted the ability to generate empty PDFs. Notably `<sile></sile` would generate but `<sile><nofolios /></sile>` would *not* because there is no output on the page and hence it never gets initialized until it's time to finish. This makes a distinction between needing to possible close open PDF handles and abort after an error and successfully running all processing and outputting a blank canvas if called for.
> Fix empty output regression

- packages/bibtex/csl/engine.lua
- packages/bibtex/csl/locale.lua
> CSL fixes (subsequent-author-substitute, LDoc typings)

- classes/base.lua
The current implementation assumes that a table is returned. I checks to see if that table is a proper SILE module, but it doesn't stop to think what happens if just a function, string, or other data is returned.
> Fix use of legacy \script function with non-modules

- build-aux/pkg.nix
- flake.lock
Does 91ca9878 look right @doronbehar?
c.f. https://github.com/NixOS/nixpkgs/pull/373209
> Sync flake with nixpkg

- documentation/c02-gettingstarted.sil
- documentation/c05-packages.sil
- documentation/c08-language.sil
- documentation/c13-tricks.sil
- documentation/sile.sil
- packages/counters/init.lua
- packages/date/init.lua
- packages/features/init.lua
- packages/inputfilter/init.lua
- packages/parallel/init.lua
Since 0.15.0, links can be line-broken, so many calls to "url" (just doing the formatting without hyperlinking) can be replaced by "href".
Closes #393
> docs(manual): Replace URLs in the documentation by actual hyperlinks

- .cirrus.yml
- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
- Makefile.am
- build-aux/que_rust_boilerplate.am
- package.json
- spec/fontmanager_spec.lua
- spec/utilities_spec.lua
Just trying to get back to green tests so I can even evaluate PRs. Not sure when this changed, maybe ICU 76?
> Update tests for ICU changing default numbering systems

- packages/retrograde/init.lua
- typesetters/base.lua
When typesetting a real book, sooner or later, the following occurs:
Most typographers would frown upon hyphenated words at the end of a page (even so more if the page ends being a right page).
Is this a bug? Well yes if SILE reportedly pretends being as good as TeX already.
Otherwise it's a "feature", implementing the missing TeX "brokenpenalty".
So here it is...
**Simplified MWE**
```
\begin[papersize=a7]{document}
\neverindent
\nofolios
\font[family=Libertinus Serif, size=12pt]
\language[main=en]
Check page break.
% Ad hoc skip to trigger the issue, with some flexibility to allow for lines to
% move around.
% Some lines of text, our sentence with a long word ("desintructionalizations")
% that we expect to be hyphenated, and some more text.
% The game is for our word to be broken, but …
```
> feat(typesetters): Discourage page breaks after hyphenated lines

- packages/indexer/init.lua
- packages/tableofcontents/init.lua
- typesetters/base.lua
Closes #1339 
- Automatically register the indexer on endpage class hook = using the 0.14.x way so any document class can use it (vs. the 0.12.x way where classes had to explicitly call a method)
- Use language-dependent sorting (collation) in indexer = Sorting based on ICU for the current language
- Support page ranges in indexer = either `none` (all pages are listed without page range collapsing) or `expanded` (consecutive pages are collapsed in full, e.g. 301-305)
- Support links to pages in the indexer = hyperlinks if the `pdf` package is previously loaded
- Add indexer options `minimal`/`minimal-two`  for page range collapsing = consecutive pages are collapsed in minimal ranges (e.g. 301-5) or minimal ranges with at least two digits (e.g. 301-05). N.B. the "minimal", "minimal-two" …
> Overhaul indexer

- packages/bibtex/csl/engine.lua
So as to make review easier, here are several fixes before I tackle with enhancements.[^1]
- fix(packages): Empty CSL macros must be suppressed = Mentioned in passing in https://github.com/sile-typesetter/sile/issues/2202#issuecomment-2566791681
> Some macros are interpreted as present while they should apparently be considered as absent. An example is the "translator" macro, which generates a "Tradução " even in the absence of translator(s) afterwards. Re-reading the CSL 1.0.2 specification, however, the only place where content suppression is clearly mentioned is on `cs:group` (acting as implicit conditional), but there's no such element here... It's still unclear to me where the intended behavior is defined...
The same entries have the macro suppressed by citeproc-js, and it sounds …
> A few simple CSL fixes

- packages/math/base-elements.lua
- packages/math/init.lua
So that primes etc. use the correct glyphs.
Libertinus Math v7.051 does not require it, but STIX Two Math 2.13 b171 and TeX Gyre Termes Math v1.543 do, for instance.
---
Closes #2223 
Yay!
I long wanted to test TeX Gyre Termes Math, so gave it shot. I had the same problem as STIX Two Math, with ssty having no effect. Both were indeed fixed by enforcing the script to "math".
We could wonder why Libertinus Math respected ssty without the "math" script while other didn't, but heh. It doesn't complain either if the script is set, so I am gonna pass on that one.
> fix(math): Script 'math' is needed for the ssty feature to work properly

- .github/workflows/build.yml
- .gitignore
- Makefile.am
- build-aux/que_rust_boilerplate.am
- build-aux/sile_dist_checksums.m4
- configure.ac
I did this manually for v0.15.9 with the aim of getting Ubuntu builds going again, but before the next release this should be automated. I'll hold off on this while I play with how it is actually used in case adjustments are needed to make it effective.
> Post vendored crates tarball

- packages/bibtex/csl/engine.lua
- packages/bibtex/csl/style.lua
- packages/bibtex/csl/utils/superfolding.lua
- packages/bibtex/init.lua
- packages/bibtex/support/bibparser.lua
- tests/bibtex.sil
- tests/bug-2054.sil
~~Currently based on #2228 - to rebase accordingly~~ REBASED
**Objectives**
**Changes**
- Some code refactors
- Some fixes and improvements
- `\nocite` command for marking an entry as cited with out actually citing it (= force its inclusion in the list of cited works, as with LaTeX)
- `\cites` command for grouped (multiple) citations
**Other notes**
On the way, I tested a few more styles, now guaranteed not to crash :rofl: and produce something at least decent :rabbit: 
- (EDIT) (obviously still Chicago author-date)
- IEEE (for the indentation rules) w/ and w/o URL.
- ISO690 (author-date) and ISO690 (numeric), both English and French styles (I was told this one is often used in French papers, so heh)... And there was a bug in our locale logic (fix: Apply default locale on locale overrides …
> More CSL features: multiple citations and paragraph format

- justenough/justenoughicu.c
Long term this shim might go away, but first I have to figure out what it is doing and make sure it is doing it right so we even have something to compare against.
Closes #359
> Clean up ICU shim

- types/length.lua
- types/measurement.lua
- types/unit.lua
Closes #2258
Accepting random amounts of garbage input after a successful match and calling it good might not have created any problems in most cases, but it does hoist the burden of validation on the end user when we could just as easily be verifying them.
This might cause errors in existing documents, but the input would also be legitimately bogus and *should* be expected to fail since the input may actually be incorrectly parsed. Just because we accepted `1ez minus 4pt plus 1gem` before and silently made it into a length doesn't mean we did it right. The user should be expected to fix the units and order until it parses successfully, e.g. perhaps they meant `1em plus 4pt minus 1em` (or maybe they meant en?).
> Make measurement and length parser more strict

- packages/bibtex/csl/engine.lua
- packages/bibtex/init.lua
~~Work in progress - pushed for information and to safeguard it before vacations~~
Supporting "position" in `csl:if` construct is one of the things that weren't implemented yet.
It's mostly used in "notes" citation styles, to evaluate and render _ibid._, _cit._ and the likes, rather than repeating the whole entry. Some "in-text" styles do use it too, but they are a minority, and unless mistaken, none of the more usual styles of that kind I checked needed it.
But of course, Chicago (fullnote), Chicago (note) or _Acta Philosophica_ etc. would be much better with it, for people who like to have those shorter references (normally to be put in some foot-or-end notes) rather than to follow author-date, numeric etc. conventions. So I wanted to address it after the completion of other refactors …
> Feat: Support CSL position condition
