- sile.in
I can't create PDF documents without this change.
> fix "attempt to index global 'e' (a nil value)"

- examples/inputfilter.sil
- packages/inputfilter.lua
Initial version of the inputfilter package with a simple example.
> Add input AST transformation tools.

- examples/chordmode.sil
- packages/chordmode.lua
- Use settings to set the offset and chord line height
- Use a custom command to define the chord typesetting style.
> Makes chordmode configurable.

- .travis.yml
This is just some odds and eds to clean up the shell scripting involved in the Travis test runs. This should make it easier to maintain and easier to read the debug log and make sense out of what step fails when they do.
> Clean up Travis recipie

- documentation/sile.sil
> fix escapes in verbatum sections of documentation and catch a few typos

- README.md
- bootstrap.sh
These are some relatively minor touchups to the build process mitigating points that confused be and hopefully making it easier for others to follow the process. Please see commit messages for more detailed explanations behind each change.
> Touchup instalation script and readme

- what-is/index.md
1 line per sentence makes diffs better, doesn't effect visual output
Also maybe consider moving what-is/index.md to what-is.md - url will be same
> what-is/index.md: fix em tag + 1 line per sentence

- packages/bidi.lua
> Always run the bidi algorithm

- core/nodefactory.lua
> Bring infinity within reach of mere mortals

- src/justenoughthai.c
> Compiler warnings

- src/justenoughicu.c
Based on suggestion from:
http://userguide.icu-project.org/strings/utf-8
See #240.
> Map UTF-16 indices to UTF-8 ones

- examples/test.sil
[Elementary, my dear Watson!](https://en.wikipedia.org/wiki/Arthur_Conan_Doyle) :smiley:
> correct author’s name

- documentation/sile.sil
Makes examples work for noobs like me ;)
> [doc] Fix missed escaping of '%' in verbatim.

- tests/bug-262.sil
- tests/bug-301.sil
- tests/bug-303.sil
- tests/bug-303b.sil
- tests/bug-307.sil
- tests/bug-309.expected
- tests/bug-309.sil
- tests/bug-317.expected
- tests/bug-317.sil
Here are some of the MWE's in open issues adapted for the test suite.
> Add tests for open issues

- documentation/sile.sil
- packages/background.lua
- tests/bug-353.expected
- tests/bug-353.sil
> Background color package

- .travis.yml
- README.md
- core/inputs-common.lua
- core/length.lua
- core/sile.lua
Fix basic issue with length parser so that tests pass on master again and touch up a few coding paradigms while mucking around.
> Cleanup master

- core/measurements.lua
> Change percent unit deprecation warning to error

- core/baseclass.lua
- core/measurements.lua
- core/utilities.lua
Here is some more stuff I've found useful. Check commit messages for detailed explanations. As with previous assorted PR's let me know if there is stuff in here you're unsure about and I'll split it up.
> Assorted niceties

- core/length.lua
- packages/cropmarks.lua
- packages/date.lua
- packages/frametricks.lua
- packages/rules.lua
- packages/textcase.lua
This is some assorted stuff I've had in my publishing toolkit(s) for a while that I find myself using a lot and re-inventing any time I don't have those libraries handy. It seems like they should just be part of SILE core but in anybody has better ideas  on how they should be implemented I'm listening...
> Assorted convenience functions

- core/harfbuzz-shaper.lua
Fix for not properly loading font data on Windows as described in #410.
> Fix loading font data on Windows.

- what-is/index.md
also a few lines later there's a \supereject that i don't know what to do with
> replace odd \em{ } in what-is page with markdown equiv

- .travis.yml
- core/sile.lua
- languages/ja.lua
- tests/frametricks.sil
I need tests working again and the master branch is full of stuff that hasn't been passing tests. This is an attempt to massage the test suite into a usable condition again.
My metrics are all different than anything Travis gives so I can't really update the `*.expected` files at the moment. However, at least with these changes I can run the suite and compare my own metrics between different commits.
Please review and merge as soon as possible because as long as this is outstanding I'm going to be going through all sorts or shenanigans with git branches to try to test my other code.
> Fix stuff so test suit even runs

- packages/ruby.lua
- src/justenoughicu.c
This is stuff from Simon's devel branch, rebased on master and with commits related to other issues removed (since they are in separate PR's with Travis having a look at them now).
I don't really know what this stuff is or weather it's ready for merging, but here it is collected in one place for CI testing. Is there more to come here?
> Stuff that does something?

- core/harfbuzz-shaper.lua
- core/inputs-common.lua
*...and two missing `local`s*
Previously part of #603.
> HarfBuzz-shaper error messages

- languages/da.lua
> fix(languages): Place Danish hyphenation rules under proper lang code

- Makefile.am
- bootstrap.sh
- configure.ac
Addresses final comments in #659.
> Tweak autoconf

- core/inputs-texlike.lua
This is an extraction (and slight cleanup) of what I did for #499 that may be useful to other packages.
Note discussion in Gitter chat [starting here](https://gitter.im/simoncozens/sile?at=5d2f77fc7dbfff3242c7241e).
This does not solve the "cart before the horse" issue where external packages will not be able to add commands to the pass-through white-list, but it does generalize the current solution for packages included in the SILE source tree.
If anybody has feedback and we decide on an approach to the catch 22, I'm happy to add it on here. Options I've thought of so far:
* command line flag to add 'enabled parsers', e.g. `sile -p lilypond,python file.sil`
* a tag syntax such as `\raw:lilypond{}` where `\raw:*` could be parsed ahead of time no matter what it was
* a tag option …
> Generalize determining if tag is a passthrough one or not

- .gitmodules
- CHANGELOG.md
- README.md
- bootstrap.sh
- core/nodefactory.lua
- core/packagemanager.lua
- package.json
> Cleanup after repository migration to org namespage

- classes/jbook.lua
- tests/jbook.expected
- tests/jbook.sil
> Fix jbook class

- packages/font-fallback.lua
> Reduce warning noise in font-fallbacks

- Makefile.am
Helps #711.
I don't actually have a non-GNU system to test this on, so @hajimehoshi I would love feedback on whether this actually works for you.
> Use only POSIX compatable shell arguments

- README.md
> docs(readme): Add explanation about ICU on macOS

- packages/parallel.lua
- tests/parallel.expected
- tests/parallel.sil
> Fix and test parallel package

- packages/counters.lua
Small typo and consistency in naming convention fix.
> Fixed documentation for counters package

- Makefile.am
These are some minor tweaks to the test facilities that I've stuck in other feature branches I'm working on, but they are really unrelated and not having them in _all_ my feature branches is making it hard to know when the tests are broken and when I'm trying to use a feature that's not in the test tooling. This should go through soon, and I'll merge into or rebase my feature branches for easier development.
> Tweak test tooling

- .github/workflows/commitlint.yml
The way to do this on Travis is too complicated (see #617), I think this will be simpler.
> chore(ci): Setup Github Action to run commitlint

- .gitignore
- .luacheckrc
- Makefile.am
- core/break.lua
- core/typesetter.lua
- packages/insertions.lua
- spec/break_spec.lua
- tests/bug-214.sil
- tests/frametricks.sil
In an effort to make manageable sized PRs, this is a collection of stuff cherry-picked from other feature branches that isn't directly related to those branches and only happened to get noticed and changed along the way. These can/should get merged sooner rather than later and shouldn't get held up by work on those other branches.
> Test and debug tooling tidbits

- README.md
> docs(readme): Cleanup installation related notes

- .commitlintrc.yml
- configure.ac
- sile.1.in
This needs some Troff help, but I'm too cross-eyed to finish tonight.
> Man page updates

- Makefile-fonts
- Makefile.am
> Fix differences between make versions and obsolete font URL

- core/typesetter.lua
Fixes #788 , would fix https://github.com/silnrsi/fontproof/issues/6.
> fix(nodes): Fix pushHbox() regression, recognize zerohoxes

- documentation/sile.sil
> docs(manual): Update class example with filename usable in v0.10.0+

- package-lock.json
- package.json
Closes #809 
Closes #810 
Closes #811 
Closes #812
> chore(tooling): Bump release management tooling versions

- .gitignore
- Makefile.am
- README.md
- m4/ax_lua.m4
- sile-dev-1.rockspec
> Setup Ubuntu packaging

- build-aux/create-homebrew-formula.pl
This automates most of the homebrew drudgery.
> chore(build): Add script to generate homebrew formula

- packages/pdf.lua
- packages/ruby.lua
- packages/tate.lua
These fix some bugs that block #616 building so I'll merge them in too as soon as it looks like the docs fully build properly again.
> Cleanup measurement stragglers

- README.md
- documentation/sile.sil
> Cleanup documentation, particularly about source installs

- .travis.yml
- documentation/sile.sil
> docs(manual): Remove reference to removed auto-guessing feature

- package-lock.json
- package.json
Closes #894
Closes #895
Closes #896
...because @dependabot can't get its act together and chain updates in a single PR or allow configurable commit messages.
> Bump all JS tooling

- configure.ac
> fix(build): Check for luarocks if not configured --with-system-luarocks

- core/inputs-common.lua
- tests/bug-892.expected
- tests/bug-892.sil
> Allow passing nil to process function

- Makefile.am
> feat(build): Add `make check` fast self-check target

- packages/rotate.lua
- tests/rotate.sil
> Fix frame rotation

- core/libtexpdf-output.lua
- tests/bug-915.expected
- tests/bug-915.sil
My version of #920.
Closes #915.
> Fix debug frame ids

- packages/ruby.lua
- tests/bug-926.expected
- tests/bug-926.sil
> fix(packages): Ruby class should not affect document language

- packages/tate.lua
> fix(packages): Tate should not affect document language (#932)

- .travis.yml
- .travis/setup_lua.sh
- Makefile-luarocks
- sile-dev-1.rockspec
This is Lua related stuff I was messing with in #909 but had to put off...
Closes #668.
> Support Lua 5.4

- core/libtexpdf-output.lua
- core/sile.lua
- documentation/c12-tricks.sil
- packages/chapterverse.lua
> Allow alternate syntax for multiple debug flags, expand debug documentation

- languages/ja.lua
- tests/bug-990.expected
- tests/bug-990.sil
> fix(languages): Stop Japanese resetting global chapter post macro

- .cirrus.yml
> ci(cirrus): Cache downloads and extracted fonts

- core/cairo-output.lua
- core/debug-output.lua
- core/dummy-output.lua
- core/libtexpdf-output.lua
- core/podofo-output.lua
- core/text-output.lua
- packages/svg.lua
> Move PDF specific SVG handling to PDF‌ backend

- core/inputs-texlike.lua
- tests/bug-1003.expected
- tests/bug-1003.sil
> Match end of passthrough environment commands more robustly

- core/opentype-parser.lua
> fix(core): Don't read zero-length name table entries

- Makefile.am
A place to stash minor fixes to be reviewed before the next release but that I don't feel like messing with now (or loosing track of the commits).
> Odds and ends

- Makefile.am
- core/cairo-output.lua
- core/debug-output.lua
- core/libtexpdf-output.lua
- core/podofo-output.lua
- core/text-output.lua
- tests/bug-1044.expected
- tests/bug-1044.sil
Closes #1012 (cf. #915)
Also gets us one step closer to being able to run multiple backends at once...
> Cleanup libtexpdf outputter

- packages/url.lua
> Remove extra space in \code from packages/url

- core/libtexpdf-output.lua
> fix(core): _drawString should take an offset

- documentation/c02-gettingstarted.sil
> docs(manual): Add NetBSD package info to install hints

- README.md
- documentation/c02-gettingstarted.sil
> Fix LuaRocks installation commands in docs

- .cirrus.yml
- .luacheckrc
- build-aux/create-homebrew-formula.pl
- classes/pecha.lua
- configure.ac
- core/sile.lua
- core/tracestack.lua
- core/utilities.lua
- languages/jv.lua
- packages/bidi.lua
- sile-dev-1.rockspec
- spec/surrogate_spec.lua
> Correct UTF8 string handling

- package.json
- sile-dev-1.rockspec
- chore(deps): Bump developer-only tooling
- chore(deps): Bump default Lua Rocks to latest
- chore(deps): Bump default Lua Rocks to latest
> Bump dependencies

- Makefile-fonts
> Fix BiDi test using correct font download

- packages/complex-spaces.lua
> feat(packages): Add complex-spaces package

- core/utilities.lua
- spec/utilities_spec.lua
> Fix UTF8 conversion utility functions

- Makefile-fonts
- Makefile-luarocks
- src/Makefile.am
> Tread delicately for macOS

- packages/pandoc.lua
Production projects have a way of bringing out weaknesses...
> Tweak Pandoc package

- Makefile-luarocks
- Makefile.am
- build-aux/ax_lua.m4
- configure.ac
- sile.1.in
Mostly lessons learned from other projects.
> Make (more) peace with autoconf and distro packaging

- .github/workflows/deploy.yml
- Makefile-fonts
- package.json
- sile-dev-1.rockspec
- chore(tooling): Bump developer tooling
- chore(deps): Bump Luarocks dependencies to latest upstreams
- ci(actions): Use same base image for all workflows
- chore(tooling): Update download link for Brill fonts
- refactor(tooling): Use more robust curl to fetch test fonts
> Housekeeping updates to deps and tooling

- core/opentype-parser.lua
> fix(math): Cope with MathVariant coverage tables being NULL

- src/justenoughharfbuzz.c
> fix(shaper): Fix memory leak in Harfbuzz library

- classes/book.lua
Closes #1276 
Minimal fix to the issue reported by @biggnome
> fix(classes): Unnumbered book sections shall not display a number in running headers

- classes/book.lua
- packages/folio.lua
> Fix plural snafu, \nofoliosthispage→\nofoliothispage

- packages/rebox.lua
> Correct rebox to not output duplicate content

- documentation/c01-whatis.sil
- documentation/c07-settings.sil
- documentation/c09-concepts.sil
Follow up to #1219 and #1264
Closes #1304
Temporarily suppresses #860.
> Document typesetter changes

- packages/bidi.lua
> fix(packages): Avoid infinite loop when re-enabling BiDi

- packages/bibliography.lua
- packages/tate.lua
> Fix issues raised by LuaHelper

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/luacheck.yml
- .github/workflows/test.yml
- .luacheckrc
- Dockerfile
- Makefile.am
- core/baseclass.lua
- core/frame.lua
- core/opentype-parser.lua
- core/utilities.lua
- hooks/build
- package.json
- sile-dev-1.rockspec
Minor updates to Docker builds, CI tooling, etc. Some is routine maintenance, some is lessons learned from other recent projects.
> Update and cleanup repo tooling

- core/languages.lua
- core/sile.lua
- core/utilities.lua
- i18n/en.ftl
- i18n/la.ftl
- sile.in
More stuff extracted from unrelated work in #1065...
> Correct missuse of pcall()

- documentation/c10-classdesign.sil
Closes #1062, also avoids #1386
> Fix bringhurst example in docs

- core/libtexpdf-output.lua
> Always output pdf on finish() even if no content

- classes/base.lua
- classes/bible.lua
- classes/book.lua
- classes/diglot.lua
- classes/docbook.lua
- classes/jbook.lua
- classes/jplain.lua
- classes/letter.lua
- classes/markdown.lua
- classes/pecha.lua
- classes/plain.lua
- classes/triglot.lua
- core/inputs-common.lua
- documentation/c10-classdesign.sil
- documentation/c12-tricks.sil
- packages/pandoc.lua
- spec/complex_frame_spec.lua
- tests/classes/testsidenote.lua
- tests/classes/testtwocol.lua
Makes life easier downstream in classes with multiple inheritance...
> More followup on class refactoring

- classes/book.lua
- packages/tableofcontents.lua
Bits noticed while porting CaSILE classes...
> Cleanup language function deprecations related to Fluent

- .github/workflows/nix.yml
- flake.lock
- flake.nix
- package.json
Closes #1388, I think.
Also probably obsoletes most of #1238.
> Bump dev tools, get Nix working

- README.md
- documentation/c02-gettingstarted.sil
- flake.lock
- flake.nix
c.f. #1388 and https://github.com/sile-typesetter/sile-typesetter.github.io/issues/30
> Touchup nix flake usage

- README.md
- classes/book.lua
- core/cairo-output.lua
- core/debug-output.lua
- core/length.lua
- core/libtexpdf-output.lua
- core/measurement.lua
- core/podofo-output.lua
- core/text-output.lua
- core/typesetter.lua
- documentation/c02-gettingstarted.sil
- flake.nix
- packages/folio.lua
- packages/gutenberg.lua
- packages/pdf.lua
- packages/rules.lua
- packages/svg/init.lua
- packages/tableofcontents.lua
- sile-dev-1.rockspec
- sile.in
Closes https://github.com/sile-typesetter/sile-typesetter.github.io/issues/30
> Post-release cleanup

- .github/workflows/build.yml
- .github/workflows/commitlint.yml
- .github/workflows/deploy.yml
- .github/workflows/luacheck.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
- .github/workflows/versioning.yml
- README.md
- documentation/c02-gettingstarted.sil
> Update CI runner environments

- packages/insertions/init.lua
> chore(packages): Work on making insertions package idempotent

- packages/background/init.lua
- packages/bibtex/init.lua
- packages/boustrophedon/init.lua
- packages/chapterverse/init.lua
- packages/cropmarks/init.lua
- packages/date/init.lua
- packages/features/init.lua
- packages/gutenberg/init.lua
- packages/specimen/init.lua
- packages/svg/init.lua
- packages/tableofcontents/init.lua
> Fixup TOC / PDF link package idempotency

- core/languages.lua
- i18n/no.ftl
> Add Norwegian localizations and cleanup warning messages

- classes/base.lua
> Make \script command properly initialize packages

- classes/base.lua
- core/cli.lua
- core/tracestack.lua
- core/utilities.lua
> Fix and improve error reporting

- core/cli.lua
- core/utilities.lua
- inputters/base.lua
- sile.in
I already started the release process, but on the side I've been dogfooding master for some projects and found a few things that should make it into v0.14.
> Last minute touchups

- packages/tableofcontents/init.lua
A small proposed PR:
Besides a cleaner separation of concerns, it can make it easier for 3rd party package writers to use the TOC in other packages (derived or not) and to reimplement the `tableofcontents` command for e.g. different presentation without having to handle the internal states and scratch variables.
(I am refactoring my "fancytoc" package to use such a method, primarily for use with my own toc package, but maybe you'll find interesting if it works with the standard toc package too?)
> Move tableofcontents loading to package method

- core/cli.lua
- inputters/base.lua
> Fix issues with --options and --class

- packages/unichar/init.lua
> Fixup unicode output in unichar section of manual

- packages/pdf/init.lua
- packages/pdfstructure/init.lua
Closes #1534.
It currently isn't possible to test this because we're using a dummy outputter for regression tests.
> Make sure PDF initialized before PDF package does anything

- packages/unichar/init.lua
- tests/bug-991-unichar.expected
- tests/bug-991-unichar.sil
Closes #991
I can't see where this would be wrong.
> Only combine unichar'ed chars with same font

- README.md
- documentation/c02-gettingstarted.sil
Do NOT sqaush the commits please
> Somewhat Refactor the Build documentation

- core/sile.lua
- packages/textcase/init.lua
> Code typos in 0.14

- .editorconfig
- .luarc.json
- core/deprecations.lua
- inputters/sil.lua
- packages/bibtex/bibliography.lua
- packages/bibtex/init.lua
- packages/bibtex/styles/chicago.lua
- packages/math/texlike.lua
I've recently started using some LSP tooling for the Lua in this project. I'm using NeoVIM, but this stuff should help out VSCode and other LSP enabled editors as well. This setup is for the sumneko Lua server which seems to be the most popular one around.
> Add developer setup for LSP enabled editors

- packages/rotate/init.lua
> Fix regression and further improve rotation package

- classes/book.lua
- documentation/c05-packages.sil
- documentation/c08-language.sil
- documentation/c10-classdesign.sil
- documentation/c11-xmlproc.sil
- documentation/developers.sil
- documentation/sile.sil
> Fix inline→block mode swith at chapter starts

- documentation/c01-whatis.sil
- documentation/sile.sil
> Fixup folios in manual

- core/sile.lua
> Allow redefinition of existing units

- inputters/sil.lua
- tests/bug-1611.expected
- tests/bug-1611.sil
- typesetters/base.lua
> Don't count some passthrough tags twice in the AST

- inputters/lua.lua
- inputters/sil.lua
- tests/bug-502.expected
- tests/bug-502.sil
> Test relaxed (and further fix) content type sniffing rules

- packages/boustrophedon/init.lua
One possible way to address #1614, by in-place modification of the vbox's output routine. It works for me, but beyond that issue I am also interested to know if that specific solution is sound[^1]
Important note: These kind of things will likely break if pushback[^2] occurs. I'm pretty sure the previous solution would have too, though!
[^1]: This is the kind of tricks I'm experimenting in a package for rotating by 180° the answers below a question (obviously additionally inverting the line order in that case, and the vglues are causing me troubles, but that's beyond the point here ^^).
[^2]: Because pusback - If I understand it correctly - occurs when the next frame has a different width (at least) and has to unpack the vbox's to resubmit the internal hbox's and nnode's to linebreaking. …
> fix(packages): Ensure a page switch does not break boustrophedon

- core/pagebuilder.lua
- typesetters/base.lua
> Fix debug functions that still assume luastd

- README.md
- documentation/c02-gettingstarted.sil
> Document how to install for Fedora

- classes/base.lua
- classes/plain.lua
- core/break.lua
- core/font.lua
- core/frame.lua
- core/opentype-parser.lua
- core/pagebuilder.lua
- core/sile.lua
- core/tracestack.lua
- core/utilities.lua
- languages/ug.lua
- languages/unicode.lua
- packages/balanced-frames/init.lua
- packages/break-firstfit/init.lua
- packages/chapterverse/init.lua
- packages/converters/init.lua
- packages/font-fallback/init.lua
- packages/grid/init.lua
- packages/insertions/init.lua
- packages/leaders/init.lua
- packages/math/base-elements.lua
- packages/math/texlike.lua
- packages/math/typesetter.lua
- packages/pandoc/init.lua
- packages/parallel/init.lua
- packages/ruby/init.lua
- shapers/harfbuzz.lua
- typesetters/base.lua
> Overhaul debug calls for speed & robustness

- classes/plain.lua
> Deprecate \listitem and \quote

- packages/autodoc/init.lua
- packages/background/init.lua
- packages/base.lua
- packages/chapterverse/init.lua
- packages/chordmode/init.lua
- packages/cropmarks/init.lua
- packages/dropcaps/init.lua
- packages/folio/init.lua
- packages/footnotes/init.lua
- packages/frametricks/init.lua
- packages/hanmenkyoshi/init.lua
- packages/lists/init.lua
- packages/pandoc/init.lua
- packages/pdfstructure/init.lua
- packages/pullquote/init.lua
- packages/ruby/init.lua
- packages/rules/init.lua
- packages/tableofcontents/init.lua
- packages/tate/init.lua
- packages/textcase/init.lua
- packages/url/init.lua
This is prep-work for tracking package dependencies in a way that would allow us to disable/unload a package after loading it.
> Add interface for packages to load packages

- core/sile.lua
- outputters/debug.lua
- sile.in
> Cleanup default module search paths, improve error messages

- .github/workflows/coverage.yml
- Makefile.am
- build-aux/list-dist-files.sh.in
- configure.ac
- core/utilities.lua
- inputters/lua.lua
- tests/049EPH.xml
- tests/balanced.sil
- tests/bug-214.sil
- tests/bug-248.sil
- tests/bug-307.sil
- tests/bug-342.sil
- tests/color-fonts.sil
- tests/footnotes-twocols.sil
- tests/frametricks.sil
- tests/process-commands.sil
- tests/space-after-command.sil
- tests/sura-2.sil
> Add CI workflow to get some code coverage back

- core/sile.lua
> Correct filename in debug info after includes

- configure.ac
> Selectively tweak Lua deps based on VM

- documentation/c12-tricks.sil
> docs(manual): Fix REPL invocation command

- core/utilities.lua
- tests/bug-1069.expected
- tests/bug-1069.sil
> Bring LuaJIT support up to 100% parity

- outputters/libtexpdf.lua
> Patch up error message when failing to load font

- .github/workflows/nix.yml
- Makefile-fonts
- build-aux/ax_font.m4
- configure.ac
- flake.nix
> Fixup build time issues

- core/deprecations.lua
- documentation/c12-tricks.sil
> Shim legacy function and over haul documentation re typesetters

- inputters/sil.lua
- inputters/sil_spec.lua
- tests/bug-1674.expected
- tests/bug-1674.sil
> Redo SIL inputter to fix regression, re-allow fragments

- flake.nix
As discussed at:
https://github.com/sile-typesetter/sile/commit/e8a56aef39eff4601490a8ccfc6bffba107b18ca
> Use `luaEnv` properly in Nix Flake

- packages/math/base-elements.lua
- packages/math/init.lua
- tests/bug-1495-inline-math-layout.expected
- tests/bug-1495-math-alone.expected
- tests/math-bigops.expected
- tests/math-fractions.expected
- tests/math-macros.expected
- tests/math-ops.expected
- tests/math-spaces.expected
- tests/math-stretchy.expected
- tests/math-subsup.expected
- tests/math-tables-mathml.expected
- tests/math-tables-tex.expected
- tests/math-variants.expected
> Fixup math font loader to work with Fira family

- classes/base.lua
> Coerce option values to booleans

- documentation/c04-useful.sil
- packages/autodoc/init.lua
Documentation for features added in PR #1672 addressing issue #1182
> Add docs for new font variations support

- outputters/base.lua
- outputters/cairo.lua
- outputters/podofo.lua
> Update Cairo/Podofo hbox debug API to match libtexpdf

- packages/infonode/init.lua
Part of a long tail of problems dating back to assuming stdlib injection of magick stuff.
Closes #1724
> Cast debug value to string

- README.md
- documentation/c02-gettingstarted.sil
Hey, I was getting started with Sile and while reading the PDF, I spotted a typo. English is not my native language, but checking some dictionaries online suggests that the word `'ether'` shouldn't be used here. 
Happy to hear what you think!
> Fix a typo

- core/cli.lua
> Let --help be a success if called explicitly

- core/break.lua
- core/cli.lua
- core/sile.lua
- core/utilities.lua
- packages/folio/init.lua
- sile.in
> Add quiet mode flag

- typesetters/base.lua
When working on understanding `typesetter:compuLineRatio()` for #1528, I couldn't make sense of the `naturalTotals:___sub(slice[n].width)` in the first loop.
So  I went on visualizing these substracted glues (cloning them and overloading their output method to draw a rule), to understand what they were. Hence:
--> This PR is just about documenting the intent of the code, without any other change.
(IMHO, the typesetter (notably) is full of such non-obvious -- or too clever -- things, and the code alone is not sufficient to understand the intent of why it does such things. It might have been clear for the developer when the initial implementation was done, but without that deep knowledge, it's hardly maintainable and even dubious at places for a casual reader. It would probably need a …
> Add more in-code comments on computeLineRatio

- spec/utilities_spec.lua
- src/justenoughicu.c
> Report on system ICU version and adjust tests accordingly

- i18n/pt.ftl
Please consider these additions to pt.ftl.
Otherwise, using the `bibtex` package to process texts in portuguese will result in error.
> Add strings to pt.ftl

- .cargo/config.toml
- Makefile-luarocks
- configure.ac
- core/pathsetup.lua.in
> Use system Lua package path from build time in run-time Rust CLI

- configure.ac
> Default configure to LuaJIT

- README.md
- classes/docbook.lua
- classes/plain.lua
- classes/tplain.lua
- core/break.lua
- core/nodefactory.lua
- core/sile.lua
- core/utilities-numbers.lua
- core/utilities.lua
- documentation/c02-gettingstarted.sil
- documentation/c03-input.sil
- documentation/c05-packages.sil
- documentation/c06-macroscommands.sil
- documentation/c08-language.sil
- documentation/c10-classdesign.sil
- documentation/c11-inputoutput.sil
- documentation/c12-xmlproc.sil
- inputters/base.lua
- outputters/debug.lua
- outputters/libtexpdf.lua
- packages/autodoc/init.lua
- packages/leaders/init.lua
- packages/lists/init.lua
- packages/math/base-elements.lua
- packages/ruby/init.lua
- packages/simpletable/init.lua
- src/justenoughicu.c
- tests/vertical.sil
- typesetters/base.lua
Mostly minor typos, but no sense in letting them live on in infamy.
> Spellcheck the manual plus some source code stuff

- packages/frametricks/init.lua
- tests/makecolumns.expected
- tests/makecolumns.sil
> Fix on command makecolumns

- classes/base.lua
- packages/base.lua
Closes #1531
Lets keep conceptual discussion in the issue, code specific review okay can be here.
> Rehash how package idempotency vs. usability works

- core/sile.lua
- core/utilities.lua
- sile.in
Closes #1882
For some reason I'm getting doubled output right now so I'll sleep on this...
> Change module load error to include suggestions of how to install 3rd party modules

- documentation/c05-packages.sil
- packages/retrograde/init.lua
> Add retrograde package to ease version transitions by restoring old defaults

- core/hyphenator-liang.lua
- languages/ca.lua
- languages/fr.lua
- languages/tr.lua
- languages/unicode.lua
> Move language specific hyphenation handling to language modules

- tests/bug-liner-width.expected
- tests/bug-liner-width.sil
- typesetters/base.lua
Closes #1984 
Quick fix after I had a sudden doubt.
~~Still need to think out craft a simpler test case, but I've already exceeded my time allocated to SILE this week by a large amount :)~~ See issue for a MWE.
> Correct discretionary width in liners

- documentation/c08-language.sil
- languages/cs.lua
- languages/es.lua
- languages/hr.lua
- languages/pl.lua
- languages/pt.lua
- languages/sk.lua
- languages/unicode.lua
> Apply double hyphenation rules to more languages

- core/hyphenator-liang.lua
- spec/hyphenator_spec.lua
> Fix utf8 hyphenator

- Dockerfile
- README.md
- configure.ac
- documentation/c02-gettingstarted.sil
- src/sile-entry.sh.in
This looks like I've done the same work twice and is duplicated with #1704. Now I need to work out the best bits of both and get them merged.
> Overhaul Docker UX

- configure.ac
- core/pathsetup.lua.in
> Allow LUA_ENV to take effect at runtime

- packages/math/base-elements.lua
> Improve error on trouble loading math fonts

- .github/workflows/build.yml
- Makefile.am
- build-aux/pkg.nix
- build-aux/que_rust_boilerplate.am
- configure.ac
- core/globals.lua
- hooks/build
- src/lib.rs
- tests/Dockerfile-dist
I set out to weed out #2078 but ran into a few other things along the way.
Closes #2078
> Fix some assorted autotools issues

- documentation/c13-tricks.sil
> Update REPL example with current length types

- configure.ac
- core/pathsetup.lua.in
Closes #2121
...at least from this side. The wrapper script on Homebrew's side also needs to go for this to work as expected.
> Accommodate vendored 'system' luarocks for Homebrew et al

- build-aux/ax_lua.m4
- build-aux/ax_lua_module.m4
- configure.ac
Our upstream contributions to make the macros cooperate with LuaJIT were merged:
https://github.com/autoconf-archive/autoconf-archive/pull/288
> Update autoconf macros as merged upstream"

- packages/math/base-elements.lua
- packages/math/init.lua
- packages/math/texlike.lua
- tests/bug-1495-inline-math-layout.expected
- tests/feat-math-display-numbered.expected
- tests/feat-math-display-unnumbered.expected
- tests/math-bigops.expected
- tests/math-fractions.expected
- tests/math-macros.expected
- tests/math-primes-asterisk.expected
- tests/math-primes-asterisk.sil
- tests/math-spaces.expected
- tests/math-stretchy.expected
- tests/math-subsup.expected
- tests/math-tables-mathml.expected
- tests/math-tables-tex.expected
- tests/math-variants.expected
> Fix math primes and asterisk

- Makefile.am
- build-aux/que_rust_boilerplate.am
- build-aux/que_rust_boilerplate.m4
> Support cross-compilation environments

- packages/verbatim/init.lua
Closes #1037, touches on documentation issue in #1837.
> Add verbatim handler for raw, touchup docs

- build-aux/list-distfiles.sh.in
> Distribute and install CSL support files

- core/languages.lua
- core/settings.lua
- languages/ar/hyphens.lua
- languages/ar/init.lua
- languages/bo/hyphens.lua
- languages/bo/init.lua
- languages/sd/hyphens.lua
- languages/sd/init.lua
- languages/ur/hyphens.lua
- languages/ur/init.lua
> Change load order so language warnings calm down

- README.md
- core/cli.lua
- core/sile.lua
- documentation/c02-gettingstarted.sil
- src/bin/sile.rs
- src/cli.rs
- src/lib.rs
> Improve 3rd party module usage prompt

- core/cli.lua
- core/makedeps.lua
- core/sile.lua
- src/lib.rs
> Fix and enhance makefile dependency list generation

- .github/CODEOWNERS
- classes/base.lua
- classes/jplain.lua
- classes/tbook.lua
- classes/tplain.lua
- core/sile.lua
- core/utilities/init.lua
- documentation/c10-classdesign.sil
- documentation/c13-tricks.sil
- inputters/base.lua
- outputters/base.lua
- packages/balanced-frames/init.lua
- packages/base.lua
- packages/insertions/init.lua
- packages/parallel/init.lua
- packages/tate/init.lua
- pagebuilders/default.lua
- shapers/base.lua
- spec/break_spec.lua
- spec/complex_frame_spec.lua
- tests/bug-244.expected
- tests/classes/testsidenote.lua
- tests/classes/testtwocol.lua
- types/color.lua
- typesetters/base.lua
- typesetters/default.lua
- typesetters/latin-in-tate.lua
Just cleaning up cruft I bumped into...
> Remove stdlib shims and normalize typesetter module layout a bit
